### ISSUE TITLE
F-Droid Version?

### ISSUE THREAD

**Issue by Hoeze** [cmeng-git/atalk-android#1]
Hi, I accidentally stumbled over this app.
As it is an Apache-licensed open source app, it would be cool to see it in the F-droid store.

Currently it is hard to find this app / this repository.
Probably the "atalk.org" domain should be registered too...

**Comment by cmeng-git** [comment]
I am more than happy to release aTalk into F-Droid, so more people can benefit from the effort that I have put in. Appreciate if you can provide me the link on how to release an apk into F-Droid. 

The registration and maintenance of a domain name requires a yearly financial commitment. I certainly would like to register atalk.org domain, however I am only an individual and does not get any financial support to do everything myself. Currently I am using the free no-ip service with a domain name atalk.sytes.net which has an online help for aTalk application. You may visit the site to find out more.

**Comment by Hoeze** [comment]
How to get your app into F-droid:
https://f-droid.org/en/docs/FAQ_-_App_Developers/#how-do-i-get-my-app-included

@ financing:
You could try to put a donation link into the readme.
A .org domain needs ~ 10,50€ per year (e.g. namecheap) which should be cheaper than play store developer access, so achieving this amount of donation should be no problem if your app gains some popularity.

**Comment by susobaco** [comment]
+1

**Comment by cmeng-git** [comment]
My home server setup is only meant for the atalk development and testing.
http://www.giadapc.com/products/minipc/cube%20series/D2308.html
It is an i7 system with 16GBytes RAM, 500GB harddisk with a 4K 32" display.
System OS is Ubuntu 16.04, ejabberd xmpp, LAMP servers and running android studio all in one.

**Comment by IzzySoft** [comment]
@cmeng-git to get you started with this, I've just filed the corresponding [RFP](https://gitlab.com/fdroid/rfp/issues/516) (Request For Packaging). You might wish to watch that one in case the maintainers need some input/help from you. Good luck!

**Comment by IzzySoft** [comment]
@cmeng-git there seem to be some issues with the JNI stuff. Could you please check via the link in my previous comment? Thanks!

**Comment by cmeng-git** [comment]
I have read your previous comment, However I am not sure what exactly is the problem.
aTalk uses some pre-compiled static libraries for optimized performance. For the aTalk development, I use Android Studio 3  on Ubuntu 16.04. The whole build process uses either the included pre-built static libraries or are built by the NDK as defined in gradle.build files. Any pre-built static library are done outside AS using android NDK toolchains.
   
Does F-Droid not allow the inclusion of any static libraries?

**Comment by IzzySoft** [comment]
> Does F-Droid not allow the inclusion of any static libraries, jars etc?

That's it, exactly. All must be build from source – at least initially; on subsequent runs, the libraries build on a previous run can be re-used (to speed up the build).

**Comment by cmeng-git** [comment]
I will try to explain the various static libraries and jars used in aTalk
build process.

1. aTalk/libs
You may delete all the files in this directory. The sub-directory contains
the results during AS build process.

2. aTalk/jni/<sub-module>/android
Please refer to ./static_library_built for instruction on building these
static libraries from source.
Currently I am trying to move this information into the cmeng-git as
individual project for easy tracking. see ffmepg-android project.

3a. aTalk/lib/installer-exclude
The sub-directory contains only jar tools use by aTalk/build.gradle during
the build process. They are not included in the final aTalk.apk

3b. aTalk/lib/bundles
The sub-directory mostly contains all the jar libraries from jitsi. These
libraries are mostly downloaded from maven repository.
However aTalk cannot use these jars directory, as they may contains modules
that are in conflict with android platform,
and hard coded paths which do not render easy inclusion in final aTalk.apk.
You may refer to aTalk/build.gradle subsection for more information.
* task jarRepackage(type: Copy, description: 'Repackage jar to avoid
conflict')
You may build these jars from source by downloading them from maven or
jitsi github repository.

4. gradle/wrapper/gradle.properties
The gradle/wrapper sub-directory is created by AS during first installation
and built.
However as the gradle build tools are upgraded by AS update over time, it
requires changes to the line
* distributionUrl=https\://
services.gradle.org/distributions/gradle-4.1-all.zip
I am not sure how to help on this.

**Comment by IzzySoft** [comment]
That explanation would have been needed over there in the F-Droid issue. I'm not a dev nor an F-Droid maintainer, so I cannot do anything with those details. I've [left a note](https://gitlab.com/fdroid/rfp/issues/516#note_62879188) for the maintainers that those details can be found here.

**Comment by susobaco** [comment]
I don't understand much either, but from what @cmeng-git  explains, I think it would be easier to create a repository and add it to the f-droid client.
https://www.f-droid.org/en/tutorials/create-repo/

**Comment by IzzySoft** [comment]
@susobaco depending on the `.apk` size, for that it would suffice to attach the `.apk` to the corresponding release here in `releases/`, so my updater could pick it for [my repo](https://apt.izzysoft.de/fdroid/repo) :wink:

**Comment by cmeng-git** [comment]
Currently aTalk release is signed using google managed key. This key is used and reflected in the Geo-Location service API. If you signed aTalk with another key, the Geo-Location feature will not be working; unless F-droid apk creator wants to request a new google Geo API key and manage this requirements as well. Note also that device pre-installed apk from android playstore, cannot update his aTalk app from F-droid. There is a conflict with the signed certificate between the two versions.

I am able to download the signed apk from android Developer Console. would it be alright o use the same apk and release in F-droid repository.  The apk size is around 28 MB currently.

**Comment by susobaco** [comment]
I'm sorry if I don't understand. But I think it would be good to "free" yourself from google services and try to use more ethical services like openstreetmaps. [Kontalk](https://github.com/kontalk/androidclient/) (And I think [Conversations](https://github.com/siacs/Conversations) is working on it, too) if you have the option to send a geolocation via google maps and openstreetmaps. Would it be very difficult to implement something like this?

https://github.com/siacs/Conversations/pull/2867

https://github.com/kontalk/androidclient/blob/5b1a291b09a0ac6dbbe2bdacc1214c25b1e7398c/app/src/main/java/org/kontalk/position/SendPositionOsmFragment.java

**Comment by IzzySoft** [comment]
@cmeng-git F-Droid man repository wouldn't accept "binary input" (neither would it "request Google keys"). And while I accept binaries for mine, there's a size limit of 20M per app (incl. multiple versions), as it runs on private space (which is not unlimited).

However, I fully agree with @susobaco concerning the "location service": why not using OSM? That would solve the issue with F-Droid, and free your app from a proprietary dependency.

**Comment by cmeng-git** [comment]
Thanks you for both of your inputs. I really would like to get atTalk to release into F-droid. However at this moment I really do not have the capacity to support another variation of aTalk.

**Comment by IzzySoft** [comment]
@cmeng-git We just figured F-Droid can **NOT** take your app in as it currently stands (see the above mentioned RFP [from this post on](https://gitlab.com/fdroid/rfp/issues/516#note_73474740). Neither can I ship it via my repo as you don't provide an `.apk` here – and it seems even if you did, it would exceed my limit of 20MB per app.

Things could change if you were able to provide an "F-Droid compatible Gradle flavor" without GMS. Also I'm curious what for an XMPP messenger needs MS Exchange?

**Comment by cmeng-git** [comment]
If you are referring to the README.md in ews-android-api plugin. actually only certain functions are used in the formatting and displaying the SSL certificate under "Settings... | SSL Certificate", the MS exchange API is not used at all.

GMS is an unique feature for aTalk, removing GMS will only save around <800K of apk size. Major apk size contributors are the native .so libraries (30%), which I am working on. However come next year, it is required for android apk to also support 64-bit lib, This will again increase the size.

I believe F-Droid 20MB size limit will be a challenge for aTalk to fulfuil, although I am constantly looking at way to reduce the apk size.

However the major issue is, personally I really do not have the resource capacity to support another variant for aTalk. aTalk still needs a lot of effort to maintain, even just to keep pace with android OS upgrade new requirements.

**Comment by IzzySoft** [comment]
Thanks for your fast response!

Just to clarify: my asking towards MS Exchange and GMS was not for size reasons: those are proprietary components not accepted by F-Droid. The size limit is not F-Droids but just with [my repo](https://apt.izzysoft.de/fdroid/repo), which runs on private space I need to budget (no organization behind that). My repo often serves as "stepping stone" for apps not yet fully ready for the official repo (e.g. if you'd be working on an F-Droid compatible flavor, and estimate that will take a while – then until it's ready, the app could be served with me).

I understand that (at least currently) you have not the capacity to maintain "another variant" (I'm no dev – but wouldn't setting up a gradle file for a variant without GMS/Exchange be a one-time task, and afterwards only require very little "permanent maintenance"?) But should you manage coming close (or even below) the 20M size, be very welcome to approach me again to serve aTalk via [my repo](https://apt.izzysoft.de/fdroid/repo).

**Comment by tuxayo** [comment]
Would a patch be accepted that makes the use of GMS or MS Exchange optional?
Only of course if it's maintainable without too much trouble.

The idea is to get an official encouragement in the case if someone would like to start working on this.

**Comment by cmeng-git** [comment]
My only concern is the version released for F-Droid and Google Play Store would have different feature sets. What would be the user reaction to this when he realizes this. If user decides to move, there is no direct upgrade path from F-Droid to Google version without uninstalling the former.

**Comment by Rudloff** [comment]
> My only concern is the version released for F-Droid and Google Play Store would have different feature sets.

We can explain that in the F-Droid description. This would not be the only the app to do that so I think F-Droid users are used to that (as long as it is clearly explained).

> If user decides to move, there is no direct upgrade path from F-Droid to Google version without uninstalling the former.

The solution to this is [reproducible builds](https://f-droid.org/en/docs/Reproducible_Builds/) but it is a lot of work to setup.

> By the way, is there any specific reason that an android user will use F-Droid instead of Google Play store installer?

Google Play is not FOSS and is not available on open-source Android distributions (Lineage OS, Fairphone Open, etc.). It is also not available in several Android forks (Amazon Fire OS and most Chinese forks like MIUI).

**Comment by streaps** [comment]
I always look in F-Droid first, just because there are so many crappy applications in the Google Play store and it's harder to find the open source apps.

If aTalk were in F-Droid, I would have discovered it earlier.

What features do need GMS?

**Comment by cmeng-git** [comment]
Please refer to the following link for more info on this feature

[StreetView & map](http://atalk.sytes.net/index.html)
http://atalk.sytes.net/faq.html#feature_02

**Comment by IzzySoft** [comment]
@cmeng-git Thanks for the links – but they don't explain what you need GMS for. In case it's about GCM/FCM, you might be interested to read [How Tutanota replaced Google’s FCM with their own notification system](https://f-droid.org/en/2018/09/03/replacing-gcm-in-tutanota.html) – but going by the permissions requested by your app, it must be something different.

**Comment by IzzySoft** [comment]
Would be good to find the culprit – as else F-Droid cannot build your app. If it uses any GMS service, that's a show-stopper here (for F-Droid that is).

**Comment by IzzySoft** [comment]
> Google play refuses to be intellectually honest labeling apps.

Even worse, it refuses to honestly list an app's permissions and whether it contains any trackers. Plus it tracks its users. Which is why on my new device I just installed, I this time even resisted the temptation to activate GCM with microG – so for the first time, my device runs completely free of Google proprietary stuff. Reasoning is the same as Morden … urn, @zz-ha-dum gave.

F-Droid is much more honest about that (and clear of that crap) – which is why we want to convince you, @cmeng-git :innocent: I rather stick with F-Droid, which now is even baked into my ROM ("LineageOS for microG" comes with F-Droid pre-installed, which even makes auto-updates possible).

**Comment by cmeng-git** [comment]
I have modified aTalk source (yet to be released) and removed aTalk dependency on plugins:ews-android-api and its library source. I have checked and found that aTalk does not use GCM/FCM at all.

I see there is no simple way to replace gms feature as aTalk uses many of its features as shown in the source file imports:
import com.google.android.gms.maps.CameraUpdateFactory;
import com.google.android.gms.maps.GoogleMap;
import com.google.android.gms.maps.GoogleMap.OnMarkerDragListener;
import com.google.android.gms.maps.OnMapReadyCallback;
import com.google.android.gms.maps.OnStreetViewPanoramaReadyCallback;
import com.google.android.gms.maps.StreetViewPanorama;
import com.google.android.gms.maps.StreetViewPanorama.OnStreetViewPanoramaChangeListener;
import com.google.android.gms.maps.SupportMapFragment;
import com.google.android.gms.maps.SupportStreetViewPanoramaFragment;
import com.google.android.gms.maps.model.BitmapDescriptorFactory;
import com.google.android.gms.maps.model.CameraPosition;
import com.google.android.gms.maps.model.LatLng;
import com.google.android.gms.maps.model.Marker;
import com.google.android.gms.maps.model.MarkerOptions;
import com.google.android.gms.maps.model.StreetViewPanoramaCamera;
import com.google.android.gms.maps.model.StreetViewPanoramaLocation;

aTalk GeoLocation implementation does not expose any of its gms interfaces to outside world. Sharing of location is not possible unless it is triggered by the users themselves.

Actually google has its own applications installed on android devices by default that will monitor user visited places. I do not see any reason why gms features need to be omitted from aTalk, as user privacy is not being compromised, unless user wishes to do so.

If Fdroid still have concern, I can include a GeoLocation option (default to off) to allow user to enable/disable so he/she would not accidentally trigger the gms location sharing.

**Comment by IzzySoft** [comment]
@cmeng-git it still imports a lot of proprietary stuff (GMS), which is a show-stopper for F-Droid – where apps must be built completely from FOSS components' sources. Apart from that: How can you tell that "user privacy is not being compromised" if you cannot analyze the code? For example, how do you know that `com.google.android.gms.maps.model.StreetViewPanoramaLocation` or `com.google.android.gms.maps.GoogleMap` do not transmit the user's location to Google servers?

"Actually google has its own applications installed on android devices by default" – not on mine. And there are many others using custom ROMs without GApps.

TL;DR: as long as any proprietary components are inside, the app cannot be listed at F-Droid.

**Comment by cmeng-git** [comment]
Thanks for the clarifications for me to understand better. Unless aTalk removes gms and all its features, look like there is no way for it to be listed in F-Droid.

**Comment by IzzySoft** [comment]
Not in the official repo, correct. But see above: that's no show-stopper for [my repo](https://apt.izzysoft.de/fdroid/repo) (if it's only that). I reserve up to 20M per app; if your APK doesn't exceed that size, all you'd have to do is to attach it to the corresponding release (and let me know the first time you've done so; after I've set it up on my end, my auto-updater would fetch them from future tags without "human intervention").

But also again: if it's just for GCM, see the Tutanota example. As for maps, there's always OSM.

**Comment by cmeng-git** [comment]
In aTalk version 1.6.0 release (20181026), I have modified the project source structure to support productFlavors built. The product built for F-Droid has excluded all closed source and proprietary libraries in the final apk generated.

For the F-Droid release build, GMS services has been removed hence its Geo-Location feature support. Any community contribution to support the feature using OSM is most welcome.

**Comment by licaon-kter** [comment]
Are these build: https://github.com/cmeng-git/atalk-android/tree/master/aTalk/lib ? They need to be...

**Comment by licaon-kter** [comment]
@cmeng-git ^

**Comment by cmeng-git** [comment]
Explanation for aTalk static lib jar:
1. lib/bundles:
These libraries belong to Jitsi, Most of them are not released to maven repository. The jar's are downloaded from jitsi internal repository.  Also some of the jar defined paths and even source need to be modified to work in aTalk. Refer to build.gradle module: task jarRepackage(type: Copy, description: 'Repackage jar to avoid conflict'). If F-Droid needs to build from source, then the respective version source have to downloaded from jitsi repository and perform build manually. 

Note: some of the jar module has been stripped of some modules and replace with source in aTalk src path. Ice has problem in aTalk which Jisti team is not willing to modify, I need to patch to make it work. see build gradle:
```
        // ice4j-2.0.0 work only with AWS disabled - otherwise hang in AWS EC2 conn.getContent()
        // System.setProperty(MappingCandidateHarvesters.DISABLE_AWS_HARVESTER_PNAME, "true")
        // Objects class only available in API-19 and above
        jarjar2(jarfile: 'libs/ice4j-2.0.0.jar') {
            zipfileset(src: 'lib/bundles/ice4j-2.0.0.jar')
            rule pattern: 'java.util.Objects',
                    result: 'org.jivesoftware.smack.util.Objects'
        }
```
2. lib/installer-excluded
These tools are used for building the aTalk apk. They are not included in the final apk file.

3. lib/native
Please refer to README_lib_built.md in ./jni/static_library_build for more information; if F-Droid wants to build from source. The native jni project have released to github

4. lib/smack
All the jar's are smack library 4.4.0-alpha2 libraries which are yet to be released to maven repository.
aTalk source was modified to use smack v4.3.x earlier. When aTalk moves to use smack v4.4.x to include some of the improved features i.e. DNSSEC and DANE verification that aTalk needs, the modified aTalk is only compatible with smack 4.4.0-alpha2 releases. The releases however are only available in https://igniterealtime.org/repo/org/igniterealtime/smack/smack-core/4.4.0-alpha2-SNAPSHOT/
If required, F-Droid can download the smack source for 4.4.0-alpha and built to be included in aTalk.

Note: aTalk smack-experimental-4.4.0-alpha2 also include source for jingle support which are not in alpha2 release. They are only in the smack pull request. aTalk is trying to migrate to use smack jingle replacing current jingle source in aTalk for streamline and take in new feature implementation in smack.
However the jar from the smack library should also work as jingle features are only access in my local separate project files.

If you want more information on Jitsi and smack release status with respect to aTalk. You can refer to their project discussion threads raised by me.

**Comment by licaon-kter** [comment]
And `/lib/bundles/` ?

**Comment by Hoeze** [comment]
As long as the sources are available, it shouldn't be a problem to build it automatically, shoud it?

**Comment by licaon-kter** [comment]
@cmeng-git 
> No change. Status same as explained in my previous comment.

Right, for some reason I did not see you mentioning them, my bad.

Anyway, this requires a lot more work than I'm able to do, hopefully someone can figure a way to build them all from source.

**Comment by cmeng-git** [comment]
Actually most of Jitsi jars are part of the jitsi-android that I had inheritated many years back. I did made some changes to use the latest jars from them on some of the libraries. As the jars are working, i did not really spent time to rebuild them from source. One reason is most of jitsi jars are built using Ant which I am not familiar with. Jitsi has taken over by commercial, the source are not so well maintain. If you really need to build from source, i really have to spent time to find the matching version source release.

**Comment by IzzySoft** [comment]
Unfortunately, that will be necessary. F-Droid insists on either building an app *completely* from sources – or not at all. Part of our [inclusion citeria](https://f-droid.org/wiki/page/Inclusion_Policy).

**Comment by cmeng-git** [comment]
Is F-Droid ok if I just find the source and send to them for their own compilation for jars that are used in aTalk apk built. aTalk does not want to include these source in the official aTalk release repository.

**Comment by IzzySoft** [comment]
You could put them into (a) different repo(s) and make use of Git's "submodule" feature. But details on this are better explained by a developer like @licaon-kter.

**Comment by licaon-kter** [comment]
I'm no developer :)

But that's the general idea, if possible.

**Comment by cmeng-git** [comment]
As I have mentioned, most of jitsi jar libraries used in aTalk, look like they are one off SNAPSHOT releases use in jitsi-android or jitsi. So these releases may not have good source control in their repository; and also lack branch release reference for Grade to fetch the source during built.

Last night, I manage to get all the library sources after google through the online repositories. In the process, I found out some of the earlier history source release are no further exist in their official repository, I have to use one that I have kept locally. Jitsi has been acquired by Atlassian; since then,  jitsi source maintenance does not get much attention. Fetching online may posses some risk, as they may not always be there.

For some of the source if they are no too big, I may just include them in aTalk project files. For those big library sources, I will include them as reference source e.g. fmj-1.0-20170519.163031-24-sources.jar in the atalk source reference directory yet to be created. F-Droid can rebuild the jar and replace all those in aTalk lib before build, or just confirm the jar in the aTalk/lib matches the source and use the jars as they are.

**Comment by cmeng-git** [comment]
aTalk release v1.6.1 has reduced the number of static libraries in ./lib/bundles to 3. This is the best I can do thus far.

**Comment by susobaco** [comment]
news?

**Comment by IzzySoft** [comment]
@susobaco unless @cmeng-git can reduce the number of "static libraries" (blobs) to zero, afraid F-Droid cannot build it.

**Comment by cmeng-git** [comment]
You may refer to my last few comments. This is a reason and limit that I can do so far. If Droid cannot accept static libraries. Can they unzip the enclosed source to build and replace the static libraries.

**Comment by IzzySoft** [comment]
@cmeng-git wasn't meant as critic, but saying exactly that: referring ti your previous comment, the current state is as far you can go.

@licaon-kter is the proposed way possible for us? Because else we only can close the [corresponding RFP](https://gitlab.com/fdroid/rfp/issues/516). 😢

**Comment by licaon-kter** [comment]
@IzzySoft https://github.com/cmeng-git/atalk-android/issues/1#issuecomment-433725006

**Comment by cmeng-git** [comment]
Does Fdroid has a tool that can verify the static libraries match the given sources in aTalk repo; and If they can accept this as alternative. Of course I can also unzip the libraries source into aTalk build directory and remove the static libraries. But my concern is that the libraries developers may not be happy their source is checked into aTalk repo. Personally I do not like this approach.

**Comment by Rudloff** [comment]
> Can they unzip the enclosed source to build and replace the static libraries.

We can build the libraries ourselves if:
* They are available in a Git/SVN/Mercurial repository.
* You can provide which commits or release we should build.
* You can provide detailed build instructions or a build script to build the libraries from source.

**Comment by cmeng-git** [comment]
aTalk release v1.7.0 (20190224) has completely removed the dependency on static libraries by allowing them to be build from source; 

Most of the static libraries in aTalk v1.6.7 are now handled automatically by gradle to fetch or build from source; with the exception of the following two i.e.
a. fmj-1.0-SNAPSHOT.jar
b. zrtp4j-light-4.1.0-jitsi-1-SNAPSHOT.jar

Due to lack of official releases of the two libraries from the developers, gradle is unable to fetch the libraries online, and they have to be built locally. Please refer to the following file i.e.:
`atalk/lib/src_reference/README.md`
for the instruction to build these two libraries from source.

Hopefully aTalk v1.7.0 has met all release requirements and accepted for release to F-Droid.

**Comment by IzzySoft** [comment]
Thanks Eng! I've triggered our bot for a rescan. :crossed_fingers:

**Comment by IzzySoft** [comment]
At least one issue still remaining:

```
ERROR: Found unknown maven repo 'https://igniterealtime.org/repo/' at aTalk/build.gradle
```

F-Droid only permits [trusted maven repos](https://gitlab.com/fdroid/fdroidserver/blob/master/fdroidserver/scanner.py#L98). Apart from that, setting up the "build recipe" [might take some time](https://gitlab.com/fdroid/rfp/issues/516#note_144613035), being not exactly trivial…

**Comment by cmeng-git** [comment]
That is smack 4.4 alpha-2 release directory. aTalk is only compatible with the latest smack alpha-2 release.

**Comment by IzzySoft** [comment]
Thanks @cmeng-git – I have to hand that over to @Rudloff again.

**Comment by Rudloff** [comment]
I am not sure why smack 4.4.0-alpha2 is not on Maven Central ([other versions are](http://central.maven.org/maven2/org/igniterealtime/smack/smack-core/)).
It is certainly possible to build the smack libraries [from source](https://github.com/igniterealtime/Smack), it just means the build recipe will be even more complex.

**Comment by cmeng-git** [comment]
Smack has just released 4.4.0-alpha2 into the following official directory on 25 Feb, 2019
https://oss.sonatype.org/content/repositories/snapshots

Does F-Droid trust this directory. If yes, then I will release a new aTalk version using this repository instead; so as to avoid building smack libraries from source.

**Comment by IzzySoft** [comment]
@cmeng-git [looks like](https://gitlab.com/fdroid/fdroidserver/blob/master/fdroidserver/scanner.py#L98) 😃

**Comment by cmeng-git** [comment]
But can the F-Droid team confirmed the following is a trusted repository
https://oss.sonatype.org/content/repositories/snapshots

aTalk needs to revert some smack related changes on many files in order to be compatible with the official released.

**Comment by IzzySoft** [comment]
You can ask @Rudloff to confirm it once more – but the link I gave should already be proof (that's what maven repos are checked against – and the one you've mentioned [is listed among the `allowed_repos`](https://gitlab.com/fdroid/fdroidserver/blob/master/fdroidserver/scanner.py#L106)).

**Comment by cmeng-git** [comment]
Thank for confirmation. Will try to release asap.

**Comment by Rudloff** [comment]
I confirm using this repository should be OK.

**Comment by cmeng-git** [comment]
aTalk v1.7.1 has been released with official smack 4.4.0-alpha2 libraries from trusted store

**Comment by cmeng-git** [comment]
aTalk v1.8.0 has included all the  jni native libraries support for ABIS i.e. armeabi-v7a arm64-v8a x86 x86_64.
The build scripts and patches have been enhanced to ease the building of these jni libraries. Please refer to ./jni/static_library_build sub-directory and https://github.com/cmeng-git/vpx-android  for more info.

**Comment by susobaco** [comment]
I'm sorry about the question. Can the FOSS version be installed from any repository?

**Comment by hub-ch** [comment]
Wait!
sorry its too long to read all comments but i read randomly, then why each updates not attach to this repository release area? that basically solves the problem.
see example: https://github.com/hub-ch/atalk-android/releases/tag/1.8.5

thats it.


there some barriers going to fdroid side, non-free dependencies etc etc
another barriers for user side if atalk depend on play services etc to run on linageos etc
for non-tech users not aware atalk source then can attach thing like https://exodus-privacy.eu.org/ analyze result one time

i'm lazy to tell more ;)

**Comment by hub-ch** [comment]
and can you write change log with each update release on repository? or add on website if it easier [i know change log has on app^^]

**Comment by cmeng-git** [comment]
The aTalk/ReleaseNotes.txt contains a full detailed descriptions of the change history for all releases.

Currently aTalk is released in android playstore, and aTalk needs to be installed/update via playstore. The own generated apk has difference signed signature from the one in playstore, therefore cannot inter-mix with android playstore version.

> and can you write change log with each update release on repository? or add on website if it easier [i know change log has on app^^]
> 
> you can add persistent apk download link to website (ex: Download aTalk Latest Apk)
> (use google drive, it has feature for update version/ change of previous uploaded file. thats how able keep static link) mostly other storage services offer it.

**Comment by cmeng-git** [comment]
Hi IzzySoft,
The latest release aTalk 1.8.2 has further simplify the jni libraries build process. 
I have checked on F-Droid store, but still do no see the aTalk release.

Is F-droid team still facing problem? Please get back to me if needs help.  

> You can ask @Rudloff to confirm it once more – but the link I gave should already be proof (that's what 
maven repos are checked against – and the one you've mentioned [is listed among the `allowed_repos`](https://gitlab.com/fdroid/fdroidserver/blob/master/fdroidserver/scanner.py#L106)).

**Comment by IzzySoft** [comment]
@cmeng-git I've asked the bot for another scan. As for the build itself, I'm the wrong person to ask (I've got no build experience at all). Pierre could answer that part better.

**Comment by Rudloff** [comment]
I will wait for the bot scan and then (if the results are OK) have another try at building it.

**Comment by cmeng-git** [comment]
> I will wait for the bot scan and then (if the results are OK) have another try at building it.

Thanks. If scan is OK, you may just do a manual build for this round. The README.md in each library provide the full instructions on how to build each library. I will see if I can further simplify the native/jni libraries build in future aTalk releases.

**Comment by Rudloff** [comment]
@cmeng-git I got almost every library to build on our server, except for 64-bits openssl.
`./build-openssl4android.sh android64-aarch64` does nothing. How do you build it?

**Comment by cmeng-git** [comment]
Hi,
Please replace the _shared.sh with the attached. I forget to update the aTalk openssl repository when I added the 64-bit support recently. The API must be: ANDROID_API=${ANDROID_API:-21}
to support 64-bit build

[Uploading _shared.zip…]()

**Comment by Rudloff** [comment]
I confirm it works with this one. Can you please update your repository with it?

**Comment by testbird** [comment]
So, once the file is up to dated in the repository, f-droid versions will be build automatically upon releases?.

**Comment by Rudloff** [comment]
Yes, we can enable auto update for this app (based on new Git tags).

**Comment by testbird** [comment]
Hey, thats great.
The tags at  https://github.com/cmeng-git/atalk-android/tags simply seem to suggest setting AutoUpdateMode to “Version +-fdroid %v” (https://f-droid.org/en/docs/Build_Metadata_Reference#733-autoupdatemode).

**Comment by licaon-kter** [comment]
@testbird No, just `Version %v` will do. Not sure where you've got that `+-fdroid`, as I can't find that in the source code. `gradle: fdroid` will take care of stuff.

**Comment by testbird** [comment]
Ah, ok I see, seems I misunderstood `+-fdroid` as adding a suffix to the f-droid build output file, to make the .apk distinguishable.

**Comment by readyblue** [comment]
+1 for F-droid version. According the survey done by lineageos.org which is alternative ROM based on Android, there is increase in number of users using their ROM without Google apps:

> There’s also been an increase in the number of users not using Google apps this year: 14.6% compared to last year’s 10%.

Source: https://lineageos.org/Summer-Survey-2-Results/

**Comment by cmeng-git** [comment]
aTalk v1.8.3 has simplified further the building of the jni libraries. You need only to execute one script for each jni library.

v1.8.3 has included the support of OMEMO Media Sharing and add support file transfer with conversations.

**Comment by testbird** [comment]
Does last week's release build on f-droid now?

**Comment by licaon-kter** [comment]
@testbird Did anyone took time to create and test a metadata file?

I've looked, but it's folder under folders for libs and lib deps :(

**Comment by testbird** [comment]
I think the success was @Rudloff

**Comment by Rudloff** [comment]
I submitted a recipe for this app: https://gitlab.com/fdroid/fdroiddata/merge_requests/4918

**Comment by testbird** [comment]
Superb!

Only thing I noticed in the description is there is no hint that this is a fork of the original jitsi-android xmpp/sip app.
But there is also no copyright history in https://github.com/cmeng-git/atalk-android/blob/master/LICENSE

**Comment by licaon-kter** [comment]
Published already, pull to refresh your F-Droid repos in client.

_(Website will be updated later)_

/close this

**Comment by licaon-kter** [comment]
@cmeng-git thoughts? https://f-droid.org/wiki/page/org.atalk.android/lastbuild_1102

**Comment by cmeng-git** [comment]
Hi,

I have pushed an update for build.gradle file to correct the lib path error.
You need to use the master repository for the aTalk v2.0.2 build.

regards,
CM Eng

**Comment by licaon-kter** [comment]
> I have pushed an update for build.gradle file to correct the lib path error.

You'll also need to [re-tag 2.0.2](https://github.com/cmeng-git/atalk-android/releases) else the next cycle will **not** actually get the fix

> You need to use the master repository for the aTalk v2.0.2 build.

Not sure what this means exactly

**Comment by cmeng-git** [comment]
Hi,

I have re-tag 2.0.2 the repository with the newly updated build.gradle
You can now build the FDroid as usual.

regards,
cmeng

**Comment by readyblue** [comment]
F-Droid builds are failing. @IzzySoft , @Rudloff can you please check #61 for this issue? Thanks

**Comment by cmeng-git** [comment]
Any update on the issue status; is the problem resolved?
Please let me know if you need any further help or clarifications.

**Comment by licaon-kter** [comment]
I'll take a look as time permits.

**Comment by cmeng-git** [comment]
aTalk v2.1.6 has upgraded openSSL library to version 1.0.2u
Please see Vulnerable OpenSSL version #88

aTalk scripts have been updated to support this built in:
./jni/static_library_built/openssl
It may be necessary to update Fdroid built scripts in order to use openSSL 1.0.2u.

**Comment by cmeng-git** [comment]
FYI:
aTalk v3.0.2 has implemented location sharing using open source osmdroid library for fdroid releases.

**Comment by IzzySoft** [comment]
Wonderful! Would be nice to have some screenshots available as well. F-Droid supports [Fastlane structure](https://gitlab.com/-/snippets/1895688) for that (summary, description, icon, featureGraphic, screenshots, per-release changelogs etc are supported). I could make a PR with what you've set up at Play if you prefer that to setting it up yourself, just let me know.

**Comment by cmeng-git** [comment]
Please help to raise the PR. All the screenshot of aTalk features are available on line:

https://cmeng-git.github.io/atalk/faq.html 
https://github.com/cmeng-git/cmeng-git.github.io/tree/master/atalk

**Comment by IzzySoft** [comment]
There you go. I didn't know which screenshots to plg from the linked documentation, so I simply used those from Play; feel free to replace. Further, I've added all short-descriptions currently available at F-Droid, and the full-description as it was present there. Again, you are free to adjust. If you have questions or need help, just say so :smiley:
