### ISSUE TITLE
zrtp-hash is ignored

### ISSUE THREAD

**Issue by MilanKral** [cmeng-git/atalk-android#101]
The value of zrtp-hash as defined in XEP-0262 is ignored and not used to check the integrity of ZRTP Hello message.
Checking of integrity of ZRTP Hello message is important to detect MitM attacks on media stream.

**Comment by cmeng-git** [comment]
The aTalk zrtp encryption libraries are actually a direct port from Jitsi source. aTalk just uses as it with only some minor changes. As such I am not familiar with the zrtp protocol setup process.

With reference to XEP-0262 standards, I see that aTalk/Jitsi has indeed implemented as required. The document does not actually mention verification of the zrtp-hash. In source, I see that that zrtp-hash is used to check for zrtp support of the participated media clients.

If you refer to ZRTPTransformEngine class, it did mention how MitM is handled.
Also in SRTPCryptoContext class, it also implements protection against replay attack i.e. checkReplay

I just wonder if the intend of zrtp-hash is not meant to alleviate the MitM. Instead this verification is left to the user to perform as described in the following site:
From https://desktop.jitsi.org/Documentation/ZrtpFAQ:
```
What ZRTP does not provide:
ZRTP cannot automatically authenticate the end-users, this is task of the users once they can talk to each other
and last but not least ‘’‘ZRTP is no replacement for common sense: check that you talk to the right person and then check the SAS
```
Please see also aTalk online help on
VoIP communications security via SRTP with ZRTP, DTLS and SDES protocol.

**Comment by MilanKral** [comment]
I'm interested in the use case described in RFC 6189, in section 8.1.1.  Integrity-Protected Signaling Enables Integrity-Protected DH Exchange.

In general, users connecting to XMPP servers are using TLS and the communication between XMPP servers should be also protected using TLS. So if we assume protected XMPP signaling layer we can extend this protection to ZRTP media.

If we assume malicious XMPP servers then the users have still to do SAS verification. So RFC 6189, in section 8.1.1. is no replacement for SAS, but only an additional protection layer.

**Comment by cmeng-git** [comment]
Thanks for the info.
Would you be able to offer help on this issue?

**Comment by MilanKral** [comment]
I will try to fix this issue

**Comment by cmeng-git** [comment]
aTalk v2.2.0 release: features included.
