### ISSUE TITLE
2.1.7 unable to send unencrypted

### ISSUE THREAD

**Issue by licaon-kter** [cmeng-git/atalk-android#104]
F-Droid, Xiaomi Android 10

```
02-05 14:04:10.579 19989 19989 E (ChatFragment.java:2413)#onPostExecute: 	at org.atalk.android.gui.chat.MetaContactChatTransport.sendFile(MetaContactChatTransport.java:639)
02-05 14:04:10.579 19989 19989 E (ChatFragment.java:2413)#onPostExecute: 	at org.atalk.android.gui.chat.MetaContactChatTransport.sendFile(MetaContactChatTransport.java:593)
02-05 14:04:10.579 19989 19989 E (ChatFragment.java:2413)#onPostExecute: 	at org.atalk.android.gui.chat.ChatFragment$SendFile.doInBackground(ChatFragment.java:2373)
02-05 14:04:10.579 19989 19989 E (ChatFragment.java:2413)#onPostExecute: 	at org.atalk.android.gui.chat.ChatFragment$SendFile.doInBackground(ChatFragment.java:2317)
```
![217unc1](https://user-images.githubusercontent.com/2282799/73847705-b6b8bb00-481e-11ea-9062-5480cce3b36a.jpg)

**Comment by cmeng-git** [comment]
I see that the last file sent activity is 2 hr after the the last success file send.

Did you know what was the status of the recipient when the last file was sent?
e.g. the recipient had gone offline and changes to different device to login.

**Comment by licaon-kter** [comment]
Nice catch but no, I just tested later and repro this error (old errors are not saved but you know that, right?). I have a screenshot at the same time too.

My contact was Conversations on the same device, online as expected.

Full login? Whatever Conversations uses `user@domain/Conversations.XXXX` I guess.

Yup repro at will, easily, after app restart and and all that.

**Comment by cmeng-git** [comment]
I have fixed the problem, and will be in next aTalk release.

**Comment by cmeng-git** [comment]
aTalk v2.2.0 release: solution included. Please verify.
