### ISSUE TITLE
Sent file bubble is on the wrong side

### ISSUE THREAD

**Issue by licaon-kter** [cmeng-git/atalk-android#105]
![217unc1](https://user-images.githubusercontent.com/2282799/73847705-b6b8bb00-481e-11ea-9062-5480cce3b36a.jpg)

**Comment by cmeng-git** [comment]
The direction of the file sent is indicated by the Red Right Arrow i.e. incoming receive and the Blue Left Arrow i.e. Outgoing sending. This is the current aTalk design UI.

**Comment by licaon-kter** [comment]
Icon....left sidemis your contact....right side is you.

Files should respect that...like your avatars.

**Comment by cmeng-git** [comment]
Actually the file transfers and messages are off two very different types, although both are displayed in the same chat session view.

At the initial design, I feel that for file transfer, user is likely to concentrate and look at the image itself.
Putting the send direction indicator next to the image make user easy to know its source.

**Comment by cmeng-git** [comment]
Updated in v2.2.1 release
