### ISSUE TITLE
[Feature Request] XHTML-IM include web images via <img> tag

### ISSUE THREAD

**Issue by Aq32** [cmeng-git/atalk-android#107]
The intention is to use emojis (possibly small gif or animated pngs) to express reactions that the default keyboard emojis don't have. 
> XEP-0071: Support send and receive of instant messages that contain lightweight text markup

I've tried using:
`<img src="https://example.com/image.png />` with an actual image url but in chat it only shows up as a generic box possibly indicating this feature isn't available. 

A feature request or extension to this could be to include a button to add an image and save it in history like custom emojis without having to explicitly download and then upload an image to send across to the recipient which is cumbersome. You could also have an option to enable/disable <img> tags or a tap on the image to open option.

**Comment by cmeng-git** [comment]
aTalk v2.2.1 has fixed the img src tag and added support:
a. Support download and display of url image in src tag embedded in xhtml message
b. Share of youtube and other social media links are tagged with thumbnail and title

**Comment by Aq32** [comment]
Can confirm: Sharing youtube links (specifically using "Share") works to show thumbnail and title. 
Image tagging worked once but then disappeared/transformed back into a square box. Subsequent attempts failed to show the image for both sender and recipient.
If you message immediately after the youtube thumbnail (same speech bubble?) then it'll also transform back into a square box. Clicking Back (top left icon) and re-entering the chat can re-show the youtube thumbnail image but doesn't work for the failed <img...></img> tag one. 

I tried using the tag <img ... /> but it seems to not work and required using <img ...></img> in the one instance where it worked (but then failed/defaulted back to square box). Typing the extra tag is a bit more typing as well which makes it rather inconvenient (even though typing xhtml is inconvenient in the first place). Maybe in the future there can be a button to add images by link/sharing or some other way to make use of xhtml similar to richtext formatting with GUI buttons for convenience. 

Regarding youtube link sharing, there could also be a GUI button or directly detect in chat when there's a youtube link. I haven't tried sharing a youtube link that isn't a youtu.be link rather than the more common www.youtube.com/watch?v=.... type links.

Out of curiosity what other social media links are enabled?

**Comment by cmeng-git** [comment]
> Image tagging worked once but then disappeared/transformed back into a square box.
That is strange, as I do not encountered this problem on my side. The image always get fetched from server and updated whenever I scroll the message into view. Below is the actual xhtml text I used to test the feature.

`<html> <img src='https://atalk.sytes.net/atalk/img/09.atalk_avatar.png' alt='aTalk xhtml demo' height='261' width='537'/> <br/>This a test of the aTalk xhtml demo <br/><a href='https://atalk.sytes.net/'>https://atalk.sytes.net/</a> </html>`

Please note that the img src link must be a secure link i.e. https://..., android does not support unsecured site access.

> If you message immediately after the youtube thumbnail (same speech bubble?) then it'll also transform back into a square box.

aTalk will not merge two xhtml marked up messages into the same message view holder. It uses the following to check for markUpText. aTalk will create a new message view holder if it detects the below isMarkUpText is true.
`boolean isMarkUpText = (bodyText != null) && bodyText.matches("(?s).*?<[A-Za-z]+>.*?</[A-Za-z]+>.*?");`

Also aTalk will only proceed to download and display the img src if the following conditions are met i.e. hasImgSrcTag
```
    boolean hasHtmlTag = body.matches("(?s).*?<[A-Za-z]+>.*?</[A-Za-z]+>.*?");
    boolean hasImgSrcTag = hasHtmlTag && body.contains("<img");
```
Please ensure the xhtml text are entered correctly and matches the above test patterns. Merging of youtube link and xhtml message seems to suggest that one of the above pattern match has failed.

The handling of ythe  \<img src... tag is handled completely by android support library. 

aTalk uses the below link support to fetch and show the image and title for shared media link.
https://noembed.com

**Comment by cmeng-git** [comment]
Any new status update? Are you still having problem?

**Comment by Aq32** [comment]
Thank you for the information yes sorry for the delayed reply I had read your message and done some testing on the day of your message but was preoccupied and forgot about this topic. Sorry again!

It seems that I was missing the <html> tag which is explicitly needed for image display to work so I can confirm that images can display now.

I haven't been able to get image animations to work at all from gif or webp. Maybe image animations is not possible with the current chat display method. Considering that animations can slow down or use up more CPU this could be a problem solving a bigger problem. An idea might be to include an option to tap a gif or animated image to play rather than automatically playing and looping animated images. (Assuming animated images are a priority which it may not be.)

**Comment by cmeng-git** [comment]
When aTalk displays an xhtml message, it made the following call, where body is the xhtml text content, and XhtmlImageParser is aTalk class to override Html.ImageGetter(), to fetch the image from the given link in "<img" src using async mode to avoid exception throws by andorid OS. After that, the fetched image placement and display is completely handled within android OS. The animation of gif is controlled by android OS, seems not supported at this moment.

`msgView.setText(Html.fromHtml(body, new XhtmlImageParser(msgView, body), null));
`

In the case where a media file is sent via file sharing, the fetching and displaying of the image is handled by aTalk, Hence aTalk is able to display the gif animation, but not for xhtml parsing and displaying.
