### ISSUE TITLE
Video stream is not encrypted when using ZRTP key exchange

### ISSUE THREAD

**Issue by MilanKral** [cmeng-git/atalk-android#108]
If video call is started using ZRTP key exchange, then the audio stream is encrypted, but the video stream is not encrypted.

If video call is started using SDES key exchange, then both audio and video streams are encrypted.

**Comment by cmeng-git** [comment]
Personally I am not familiar with ZRTP; aTalk ZRTP is ported directly from jitsi. I just did a video call with ZRTP between two samsung android devices; I check the call info. It indicates that both video and audio are encrypted with ZRTP. No sure how you performed your test, and concluded that only audio is encrypted.

![image](https://user-images.githubusercontent.com/7959606/74240472-06aeea80-4d15-11ea-8f0a-342da7f611bd.png)

**Comment by MilanKral** [comment]
This is my error, the video stream is encrypted in ZRTP.

I have been experimenting with different video resolutions and there have been problems in establishing of the video stream. So this is not related to ZRTP.
