### ISSUE TITLE
Messages in speech bubbles and editing messages issues

### ISSUE THREAD

**Issue by Aq32** [cmeng-git/atalk-android#110]
With the message bubble the two ticks only confirm receipt of the latest message? If there's a message sandwiched in the same speech bubble that only has one tick but then the user sends another but successful message then the previous one might not be sent but the speech bubble will still show two ticks indicating nothing went wrong. Is there a way to re-send or show that all messages are sent?

When editing the last message the whole message bubble seems to be duplicated and everything is in italics. Perhaps it would be better to only make the last line added by aTalk "(edited at [time])" be in italics? Is it necessary to show the original as well as the new changes? Perhaps the original message could be folded and if tapped can be shown? This part is more of a feature request.

Another issue is that a speech bubble can have multiple messages/lines which when edited is broken and newlines are lost. Everything is placed into one single line wrapped message. Can you confirm and is there a way to keep the original line breaks and formatting?

**Comment by cmeng-git** [comment]
aTalk v2.2.0 release:
All solutions implemented.
Prefix 'X' for undelivered message in merge messages view holder.

**Comment by Aq32** [comment]
Can confirm that the duplicate messages issue is gone in the new version and that editing multiline messages are handled now. Thanks!

What are your thoughts on the formatting for edited messages? In the new aTalk version (2.2.0) there is now the edited post-text and without the edit timestamp. Is this a purposeful removal or would you be interested in something like long-tapping to select and tapping on an "info" icon to show more information about individual messages like when a message was edited?

**Comment by cmeng-git** [comment]
Only consecutive messages and all are within 60s period  (i.e. first to last messages) are grouped and shown in the same view holder.  For practical purpose, at worst, the edited message is <60s of the main date that is already shown in the view holder. That is the reason I decided to only retain the "edited" and remove the timestamp.
