### ISSUE TITLE
orbot/Tor Support

### ISSUE THREAD

**Issue by zwiebelfreund** [cmeng-git/atalk-android#115]
Hello,

can you add support for orbot / Tor to the Network settings so that i can connect to an .onion jabber Server?

I did not found settings to change dns Server, this is nesessery for tor, only change the Proxy/Socks did not work

**Comment by cmeng-git** [comment]
Please online help. It is already supported as BOSH.

**Comment by zwiebelfreund** [comment]
i don't understand how to use a BOSH URL, is BOSH a seperate Server to install before?
If not, can you explain what settings i have to insert to use tor?

**Comment by cmeng-git** [comment]
Please refer to help link provided in my previous comment.
