### ISSUE TITLE
otr crypt on one to one connection

### ISSUE THREAD

**Issue by vampiebar** [cmeng-git/atalk-android#116]
Hello,
What happened to OTR ( in one to one direct message - not room/group ) ?
In group OMEMO id default..
but in between 2.1.7 version client of atalk and with 2.2.0 I cannot see ( in 2.2.0 ) OTR crypt on padlock..
just Unencrypted and Omemo.. OTR is not in list..

**Comment by cmeng-git** [comment]
OTR protocol can only one to one. There is no group chat for OTR.

**Comment by vampiebar** [comment]
Yes I know I am talking about one to one..  Between 2.2.0 and 2.1.7 version one to one there is no OTR...
in combobox list.

**Comment by cmeng-git** [comment]
I have confirmed there is no problem on OTR in aTalk v2.2.0.
Please check and verify that the contact is online. OTR does not support offline message delivery.
