### ISSUE TITLE
Make fingerprinting of ZRTP connections harder by using a different ZID for each callee

### ISSUE THREAD

**Issue by MilanKral** [cmeng-git/atalk-android#122]
Each instance of ZRTP has a unique 96-bit random ZRTP ID, or ZID, that is generated once at installation time. The ZID is transfered as cleartext in ZRTP protocol. Because of this it is very easy for a passive attacker to identify each ZRTP instance and see a lot of metadata over time.

To make this passive observation harder use a different ZID for each peer in the ZRTP communication. This is allowed according to RFC 6189.html section 4.9
"However,
   it is specifically not precluded for an implementation to use
   multiple ZIDs, up to the limit of a separate one per callee.  This
   then turns it into a long-lived "association ID" that does not apply
   to any other associations between a different pair of parties. "

Also allow the user to generate new ZID when needed. (The users have then to do a SAS checking after this operation).

**Comment by cmeng-git** [comment]
After the merged, I realize that the ZID reset is global and applied to all users. Should the ZID reset be per user account, hence require to move the option to Account Settings.... | User | Call Encryption settings.

**Comment by MilanKral** [comment]
I will see how to change the behaviour so that each Account has a separate salt value from which the ZID is calculated.
