### ISSUE TITLE
New Light and Dark Theme

### ISSUE THREAD

**Issue by Aq32** [cmeng-git/atalk-android#124]
The new light and dark theme is a good addition for GUI design thanks for making steps towards this and including it! 

An improvement would be to also include the largest white areas for the dark theme. For example the main contacts view still shows a large area of white which can be glaring in a dark room which is one of the reasons for a dark theme to begin with (as well as reducing battery life on some phones). Similarly in chats the speech bubbles and background behind the chat bubbles are also still bright and not consistent with the intent of a dark theme. 
Understandably the background colour is also used to indicate whether chat is encrypted or not so maybe there can be two darker colours for encrypted and not encrypted for the dark theme too.

Future suggestion, would it be possible to customize these themes manually so there could be a folder for people to use their own custom theme files be it xml/html/css to set their own colours for each area of the GUI? So when the app opens (or when the user goes into settings) it can check within the folder of themes for users to select the theme file to use. These theme files would customise the colours of everything you already changed and include the colours of things mentioned above.

**Comment by cmeng-git** [comment]
aTalk v2.4.7 release has changed the light theme background from grey50 to grey200. This is the lowest brightness aTalk can accept. Anything higher than that, the light theme background will look more like grey/dark color. If you still feel it is too bright, you may have to lower your phone overall brightness.
