### ISSUE TITLE
Chat History

### ISSUE THREAD

**Issue by Aq32** [cmeng-git/atalk-android#125]
In the options there's a "Chat history logging" option and "Show history" option. Where is the chat saved? I've had a look inside the aTalk folder but there doesn't seem to be a text file or any form of history logging afaik. 

I've tried scrolling back in chat too but at a certain point the chat loops back into the most recent messages so I'm not entirely sure the chat history is logged or saved down. If you do implement a chat history save file it might be useful to separate chats into separate files by day or month or year with the option available by the user.

Another feature request too, would it be possible to also include video and voice call start, duration and end times into the chat window and chat history log file?

**Comment by cmeng-git** [comment]
aTalk uses mySQL database to save its chat history log. The DB is resided in the project specific directory inaccessible to user.

You can only access to this database using a aTalk debug version. Where there is an "Export aTalk SQL Database' option in the Account Settings... | Sweep icon.

Currently all the call history are actually saved in the DB, but aTalk yet to implement a viewer for it.

**Comment by Aq32** [comment]
Ah I see. I had a look on aTalk's website and didn't see a link for the debug version so I assume that it has to be manually compiled? Are there links for different compiled apk installers for the different versions (official main version, debug and beta)?

**Comment by cmeng-git** [comment]
You can get a latest copy of the debug version from the link below:
https://atalk.sytes.net/releases/atalk-android/aTalk-playstore-debug.apk

Please note that debug version has a different signature key as from FDroid or Playstore released version. When installing an apk with different signature, android will prompt you to uninstall the previous version before allowed to proceed with the new apk installation.

**Comment by cmeng-git** [comment]
Call history records UI has been added in v2.2.4. Please verify.
