### ISSUE TITLE
Google Play Services dependency

### ISSUE THREAD

**Issue by Reue** [cmeng-git/atalk-android#128]
aTalk has a "Google Play Services" dependency. Please remove it, because Google Play Services is not free software and acts like a virus. For instante, when you remove the "Location" permissions, on Google Play Services, it automatically and secretly reactivates them, in background.
We don't need Google Play Services and its proprietary. Thanks in advance.

**Comment by cmeng-git** [comment]
Please install aTalk from Fdroid repository which already has the feature removed.

**Comment by cmeng-git** [comment]
Please note aTalk v3.0.2 release has implemented location sharing option, but using the open source osmdroid library instead of gms libraries.
