### ISSUE TITLE
Invitation for chat rooms doesn't work

### ISSUE THREAD

**Issue by Reue** [cmeng-git/atalk-android#129]
When you send an invitation to someone, in order to participate in a chat room, either:
- the invited user never receives the invitation;
- or the invited user receives the invitation but he is presented with a "popup" with the following message: "The [Chat_Room_Name] chat room has requested a password.". This "popup" asks the invited user to fill the following fields: [username] ; [password]. The problem is: We can fill the password field but it is impossible to fill the username field! We click on that field and it does not allow any input! And, as it is impossible to fill that field, when we click on "Ok", trying to accept the invitation, the following error message appear: "Please enter a value for all fields". And, of course, we are not allowed to accept the invitation.

This behaviour has been tested in several Android smarphones and several accounts, always with these results.

**Comment by cmeng-git** [comment]
> the invited user never receives the invitation;

please see https://github.com/cmeng-git/atalk-android/issues/121; if you are having the same problem. Otherwise please send me the debug for both the sender and recipient after you have performed the invitation.

>  "popup" with the following message: "The [Chat_Room_Name] chat room has requested a password.". 

Is a bug in aTalk. The field is supposed to be not-editable and to be filled by aTalk with the room nickName. Have fixed the problem for next release.

**Comment by cmeng-git** [comment]
> Is a bug in aTalk. The field is supposed to be not-editable and to be filled by aTalk with the room nickName. Have fixed the problem for next release.

Problem fixed in android v2.2.2 release. Please verify.

If you still facing the below problem, please provide more info. Otherwise I will treat as NPF. 
> the invited user never receives the invitation;
