### ISSUE TITLE
status message / user's address is hidden

### ISSUE THREAD

**Issue by streaps** [cmeng-git/atalk-android#13]
Minor UI issue:

If a user contact has set a status message, the status message is displayed instead of the jabber address. How can I figure out the jabber address, if it is hidden by a status message? Not even "Contact Info" shows the address.

I think it's also a potential phishing risk (even if I don't think it is a real threat at the moment). For example it's possible that a contact set the status message to "fakeuser@example.com" and it looks like it is the real jabber address.

**Comment by cmeng-git** [comment]
If you tab on the avatar of the contact in the main menu, it should display the contact jabber address.
