### ISSUE TITLE
[Feature Request] Text to Speech (TTS)

### ISSUE THREAD

**Issue by Aq32** [cmeng-git/atalk-android#132]
Would it be possible to implement Android's TTS to read to earphone and/or speaker chat messages? 

Some use cases for TTS might include:
- Voice chat when real time chatting is preferred but one participant cannot/chooses to type instead for whatever reason(s)
- Accessibility for users who may find reading difficult or inconvenient for multitasking reasons (could be typing in multiple chats or using other apps) but can listen to TTS.
- Clarity for notification events and more specificity regarding events (further elaborated below)

Thoughts on the settings:
- An tick/checkbox within each (group/user) chat could be made for people to enable/disable TTS per chat
- A new section in Settings can be made to manage TTS. 
- A global TTS option to turn off/on all TTS.
- An option under TTS settings would enable/disable TTS messages read out loud per individual notification if a specific chat window is not in focus or aTalk is not in focus or phone screen off. 
- - 2 independent sub-option tickboxes for notifications could let users customise what to hear: the message source ((the group name and) the messenger's username) and then the message itself or both/everything or nothing. If the last sub-option "message" is unchecked then it might be enough to hear TTS say: "[(In Group_Chat_Name) - Username] replied" as opposed to the message source+message or just the message spoken out loud.
- - A sub-option might use TTS only to read out loud when the user switches to the specific chat where the message is received, such that a user can listen to the TTS twice (from the notification and chat again) or once (or never). Hearing once can happen if TTS notifications are turned off for Android DND (or Silent mode) or if disabling (in the previous/above point and below point) both message source and message TTS from notifications (as option below explains).
- Under the existing Notifications -> Events settings TTS to read out events could be a new option for each event. It can be particularly useful if it provides more information such as Incoming File to describe file type or file name and/or completion of file transfer (if auto accepted). Enabling TTS as an event notification option could be more straightforward for the user than recognising sounds/vibrations and then working out what happened.
- - 2 tick/check boxes to allow TTS output to earphones and/or speaker but maybe the Android TTS system will default to prioritise earphones first then speakers rather than user choice option(s) which for me still works out fine since I'd personally prefer it pipe to earphones if available rather than speakers but for some people the extra option is nice.

For messages or strange message sources, Android's TTS should handle special characters or emojis but you will have to deliberately ignore XHTML tags before sending it to the built-in TTS to speak out loud.

This probably seems like a lot to implement but even a basic message pipe to use the built-in Android TTS system and settings would be a nice additional feature for aTalk that can allow more multitasking and less screen wait-watching.

**Comment by cmeng-git** [comment]
Most of the request features implemented in v2.2.3. Please verify.

**Comment by Aq32** [comment]
Text to speech works but it can be a bit inconsistent. If I'm still in the chat I can hear the tts but if I'm in the settings then I only hear the sound notification without the tts. The General TTS Setting to delay TTS is really handy for variable sound notification alerts. I can also confirm that TTS works outside of the chat and works as expected through the earphones when plugged.

**Comment by cmeng-git** [comment]
> if I'm in the settings then I only hear the sound notification without the tts
aTalk v2.2.4 released has fixed the problem. Please verify
