### ISSUE TITLE
When peer uses both Jingle capable and Jingle incapable software Calling is not possible

### ISSUE THREAD

**Issue by MilanKral** [cmeng-git/atalk-android#133]
A peer uses two different XMPP clients with the same JID (but different resources). One XMPP client is Jingle capable, the other is not capable of Jingle.

First the Jingle capable client connects.
Second the Jingle incapable client connects.

After this the Call and Video call buttons in aTalk contact list for this peer are hidden.
But this buttons should be visible because the first Jingle capable client is still connected and it should be possible call the peer.

**Comment by cmeng-git** [comment]
Can you try to change the client priority higher for the one that supports jingle to see it work.

aTalk current design is based on more recent contact or contact with highest priority to communicate with.

**Comment by cmeng-git** [comment]
Yes, there is a problem on call button. Currently aTalk only consider the most recent contact activity to show the call buttons. I was in the middle of implementing a fix for it, however I am now stuck to do any further work on aTalk due to below reported problem to google team, waiting for their assistance:

https://issuetracker.google.com/issues/153594531

**Comment by MilanKral** [comment]
I can't see the text of the issue 153594531.
It requires a Google Account login.
Please copy it here.

**Comment by cmeng-git** [comment]
It is good just to refer to this instead. 

https://www.google.com/url?q=https://discourse.igniterealtime.org/t/smack-4-4-0-alpha3-20200404-causing-problem-in-atalk-build-with-incompatible-types-for-classes-implementation-of-extensionelement/87668&sa=D&usg=AFQjCNFP9ESvwTu4JG19JuGAR6KeVv_X3Q

**Comment by cmeng-git** [comment]
Fix implemented in v2.2.3. Please verify

**Comment by MilanKral** [comment]
fixed in aTalk v2.2.3
