### ISSUE TITLE
Build error Smack

### ISSUE THREAD

**Issue by MilanKral** [cmeng-git/atalk-android#134]
I get the following build error

atalk-android/aTalk/src/main/java/org/jivesoftware/smack/tcp/XMPPTCPConnection.java:115: error: cannot find symbol
import org.jivesoftware.smack.util.dns.HostAddress;
                                      ^
  symbol:   class HostAddress
  location: package org.jivesoftware.smack.util.dns

were there any recent changes in the Smack library?

**Comment by cmeng-git** [comment]
There is a snapshot update to smack-4.4.0-alpha3-20200404. You need to wait for next aTalk release.
