### ISSUE TITLE
Crash when opening "Account settings"

### ISSUE THREAD

**Issue by MilanKral** [cmeng-git/atalk-android#136]
When opening settings for an account under different account translation the application crashes.

Scenario:
1. Select English translation.
2. Register a XMPP account
3. Select a different translation, for example German or Russian.
4. Try to modify account settings for the registered account.
5. Application crash

The problem seem with string service_gui_settings_BOSH_PROXY which is translated and used for P_KEY_PROXY_CONFIG.
JabberPreferenceFragment.onPreferencesCreated uses P_KEY_PROXY_CONFIG in:

findPreference(P_KEY_PROXY_CONFIG).setOnPreferenceClickListener(pref -> {
            BoshProxyDialog boshProxy = new BoshProxyDialog(getActivity(), jbrReg);
            boshProxy.show();
            return true;
        });

**Comment by cmeng-git** [comment]
Yes, It is my oversight. All preference key must not get translated. Have fixed it for next release

**Comment by cmeng-git** [comment]
aTalk v2.2.3 released, please verify

**Comment by MilanKral** [comment]
Fixed with aTalk v2.2.3 release
