### ISSUE TITLE
aTalkApp.getResString does not translate strings

### ISSUE THREAD

**Issue by MilanKral** [cmeng-git/atalk-android#138]
aTalkApp.getResString always returns the english string without translation.

How to reproduce:
1. select non-english language
2. multiple times select the menu option "Hide offline contacts", "Show offline contacts". The menu option is at first in the selected language. Then shows only the english strings.

**Comment by cmeng-git** [comment]
Problem fixed for next release

**Comment by cmeng-git** [comment]
aTalk v2.2.4 released with the fix. Please verify

**Comment by MilanKral** [comment]
Fixed in aTalk v2.2.4
