### ISSUE TITLE
IPCall auto reconnect when client IP is changed

### ISSUE THREAD

**Issue by dingdongnigetou** [cmeng-git/atalk-android#139]
ISSUE:
  IPCall is failed when I switch the network of the phone.

Solutions:
* I found out there is an feature on coturn, for mobility, and check the [RFC](https://tools.ietf.org/html/draft-wing-tram-turn-mobility-02), but this also need client to do some works which is not implemented on ICE4J lib.
* Maybe client shutdown the old channel and create an new channel by following the whole steps (ICE -> exchanged -> ZRTP -> connected), seems it costs expensive...

So any ideas for that ?

**Comment by cmeng-git** [comment]
If you change the phone network while an IPCall is in progress, you have basically break all the protocol connections i.e. xmpp server connection, and all the RTP and RTCP channels setup for the media call.

aTalk currently will auto-reconnect and re-register with the xmpp service.

However to reconnect the broken media call, basically you have to go through the whole call setup process e.g. dialing, calling, ringing and call answer. There is little to do with ice4j. You are requesting aTalk to automate all these manual call setup process when the network connection has changed. I have to decline such a request.

**Comment by dingdongnigetou** [comment]
> However to reconnect the broken media call, basically you have to go through the whole call setup process e.g. dialing, calling, ringing and call answer. There is little to do with ice4j. You are requesting aTalk to automate all these manual call setup process when the network connection has changed. I have to decline such a request.

Yes, im totally agree what you said. 
Maybe implement the mobility feature is the best way to fix this. Which need ICE4J to process **MOBILITY-TICKET** [attribute](https://tools.ietf.org/html/draft-wing-tram-turn-mobility-02#section-3.3) from turn server. And also the local socket need to be rebound to an new local address. Then no need to go through the whole call setup again.

**Comment by cmeng-git** [comment]
Would you work with ice4j development team to add the feature.

I did not study in details of the proposed changes. Please note that even if the proposal can re-establish the media channels, the ZRTP MitM protection implementation, however will discard all the new media stream received.

**Comment by dingdongnigetou** [comment]
> Would you work with ice4j development team to add the feature.

My pleasure, maybe when i have enough time i will patch it.

> I did not study in details of the proposed changes. Please note that even if the proposal can re-establish the media channels, the ZRTP MitM protection implementation, however will discard all the new media stream received.

Wow, it seems it's a difficult way...

**Comment by cmeng-git** [comment]
Many thanks for your offer.

**Comment by cmeng-git** [comment]
close: no within aTalk ability to support this.
