### ISSUE TITLE
[Feature request]  IPCall in muc.

### ISSUE THREAD

**Issue by dingdongnigetou** [cmeng-git/atalk-android#145]
How to support this feature?

It seems we need to shared the unique `AudioRecord` between multi-stream.
Or use the [jitsi-meet](https://github.com/jitsi/jitsi-meet) lib ?

Any researches to share?

**Comment by cmeng-git** [comment]
In Jitsi earlier day, the team has implemented videoBridge which is a part of the XMPP protocol, but seems it does not get much attention this day. I did a quick test many years back, but it was not working then. No sure what is the status today.

Jitsi-meet is the latest implementation but based on webrtc. Not sure if you are able to integrate with client running xmpp. I believe jitsi team have worked on this for at least 5 years. There are some jitsi-videobridge document on jitsi site but no sure if they are still there. 

In either case, the integration is not simple and need a lot of effort. aTalk has no resource to do any of these at this point.

**Comment by dingdongnigetou** [comment]
Thanks for your reply.

Why don't we integrate with webrtc just like Converstations did? webrtc seems support multi-chat on VOIP.

**Comment by cmeng-git** [comment]
Are you able to access the link:
https://github.com/siacs/Conversations/tree/jingle

My access to the link is blank.

**Comment by ericschdt** [comment]
> Are you able to access the link:
> https://github.com/siacs/Conversations/tree/jingle
> 
> My access to the link is blank.

It has already been merged into the master branch and the redundant jingle branch has been deleted. ;)

**Comment by dingdongnigetou** [comment]
> > Are you able to access the link:
> > https://github.com/siacs/Conversations/tree/jingle
> > My access to the link is blank.
> 
> It has already been merged into the master branch and the redundant jingle branch has been deleted. ;)
> See the commits: https://github.com/siacs/Conversations/commits/master

Yes, pls check this.

**Comment by ericschdt** [comment]
About Jitsi Meet: See also https://github.com/jitsi/jitsi-meet/issues/6235

**Comment by cmeng-git** [comment]
Not feasible  in aTalk implementation to use jitsi-meet; complete software architecture change.
