### ISSUE TITLE
timeout for messages

### ISSUE THREAD

**Issue by vampiebar** [cmeng-git/atalk-android#149]
Is there anything for deletion of messages after read such as 30-60-90 seconds?
like in telegram?

**Comment by cmeng-git** [comment]
Auto deletion of the messages have to be performed by the client that has received the messages.

aTalk is an  XMPP client following standard xmpp protocol. aTalk can implement the feature, however it is difficult to enforce. Any buddy with client installation other than aTalk will immediately defeat the feature.
