### ISSUE TITLE
Had error when build project: CreateProcess error=2, The system cannot find the file specified

### ISSUE THREAD

**Issue by thanhnhan290488** [cmeng-git/atalk-android#15]
I had geting source and build with android studio. And out put error: CreateProcess error=2, The system cannot find the file specified

**Comment by cmeng-git** [comment]
My build environment is using ubuntu. The source need to be built under linux

**Comment by cmeng-git** [comment]
I am assuming the problem you encountered is due to improper environment. So I am closing the issue.
