### ISSUE TITLE
Don't auto download in public MUCs

### ISSUE THREAD

**Issue by licaon-kter** [cmeng-git/atalk-android#152]
...since anyone can post anything there, while in a private MUC or an 1:1 there's an inherent trust in its members.

**Comment by cmeng-git** [comment]
The control of the chat room creation or discussion subject should the responsibility of the service provider administrator. 

Stop downloading of chatroom from server, means chatroom bookmarks is also no working.

**Comment by licaon-kter** [comment]
Are we lost in translation?

The client, aTalk, can choose to ONLY show the download button and NOT auto-download random **files** posted by random strangers in public MUCs.

The service admin, the creation and all the other stuff you mention, bookmarks (!?), are not related to my issue.

**Comment by licaon-kter** [comment]
Please reopen.

**Comment by cmeng-git** [comment]
Sorry, I misunderstood your question.
There is already an option to disable auto download file.

![image](https://user-images.githubusercontent.com/7959606/84784932-77e11000-b01d-11ea-9928-6cfe33b14efa.png)

**Comment by licaon-kter** [comment]
See my first post, I want autodownload...but not everywhere. Yes Conversations has this "feature" :)

**Comment by cmeng-git** [comment]
> Yes Conversations has this "feature" :)

I was unable to find this option in Conversations, except the one similar to aTalk implementation. How do I access to this option to disable auto download in public chat room.

In my previous discussion with you on:
[Unencrypted photos don't show a preview when received by Conversations #84](https://github.com/cmeng-git/atalk-android/issues/84)

I am not sure if this is what you are referring to; conversations does not download file or show a preview of the shared file if the file is in plain mode. Conversations will proceed to download and show preview of an encrypted file which fulfill the auto download condition.

**Comment by licaon-kter** [comment]
@cmeng-git it's by default in Conversations, nothing to toggle.

#84 is about 1:1 chats, this is about MUCs

I'm talking about public MUCs, these can't be encrypted.

**Comment by cmeng-git** [comment]
> #84 is about 1:1 chats, this is about MUCs

The exact same behavior applies to both 1:1 (when user is offline) or MUC chat in Conversations. Currently Conversations does not auto download an unencrypted file if it was sent via HTTP upload.  It happen that users sharing of file in the joined public room does not have OMEMO encryption. All file sharing therefore has to be sent via HTTP upload. This is more like a shortcoming rather than design intent.

**Comment by licaon-kter** [comment]
No, encrypted and unencrypted files are autodownloaded in private MUCs and 1:1

Files are not autodownloaded in public MUCs

I never said Jingle or HTTP, fair, to make it clear, I always meant HTTP.

**Comment by cmeng-git** [comment]
> The exact same behavior applies to both 1:1 (when user is offline)

For 1:1 chat, you need to put the recipient offline before sending the file. On complete of sending the file, then put the recipient online.

For MUC: please try again. You need to send the file in unencrypted mode. 

Otherwise you will not see the problem that I have mentioned

Below is the screenshot of the test perform on Conversations v2.8.7:
![image](https://user-images.githubusercontent.com/7959606/84861300-4f9bf480-b0a3-11ea-9cc7-1d7a076c20c6.png)

**Comment by licaon-kter** [comment]
I don't have 2.8.7 yet, but 2.8.6
![looks like this](https://i.imgur.com/6XvIRxl.jpg)

I only use Conversations for testing

**Comment by cmeng-git** [comment]
Sorry the screenshot looks more like a 1:1 chat, or a private chat in MUC. I see only one name being listed at the top.
In my case for muc, the screenshot shows that there are two participants in the room.

**Comment by licaon-kter** [comment]
A private MUC has a title...yes.

Private chat in MUC shows "X has whispered"

My test accounts have the same avatar.

Are you implying that I lie or?

**Comment by cmeng-git** [comment]
> Are you implying that I lie or?

Please keep to the topics for discussion. both of us are professional and I only keep the discussion on subject, never on person.

The reason I raise the issue is that I am not sure what is a private MUC, I am unable to get a definition of it from XEP standard.

Can you open the room on aTalk, and capture the chatRoom info for me to understand what is a private muc.

**Comment by licaon-kter** [comment]
Conversations uses the guidelines defined here: https://wiki.xmpp.org/web/Sprints/2019_January_Brussels/Pad

**Comment by licaon-kter** [comment]
Chatroominfo says: members only, persistent, moderated, non-anon (these 4 are checked)

**Comment by cmeng-git** [comment]
Now I understand. Member only and non-anonn room, all user Jid must be provided, Conversations uses jingle file transfer protocol and not HTTP file upload. Therefore Conversations is still able to show preview. For http file upload, it shows only  the link, not by design.

**Comment by licaon-kter** [comment]
No jingle is used, unless filesize is bigger than max HTTP size or HTTP_upload is not available.

Anyway, this issue is not about private rooms.

**Comment by cmeng-git** [comment]
![image](https://user-images.githubusercontent.com/7959606/84964833-c4247100-b13f-11ea-8fb9-33d4cdb22d6a.png)

I just did a test with private MUC with both an aTalk and 2 x Conversations members joined the room. The snapshot is for one of the Conversations member. A same encrypted image file was sent from aTalk, then from Conversations member.

From the conversation debug log, and the derived conclusion is that the file is sent via HTTP file upload in both cases. However conversations will proceed to retrieve the file from the server if is was sent from conversations client; but not the case when the file is sent from aTalk. I believe that it is likely an underlining exchange of info between conversations clients when doing file sharing.

As such, showing of the received file as preview or link has no connection whether the room is private or public i.e. is is not a design intention or feature being implemented not to download file in public room. So aTalk will not change its ability to auto download files that are shared in public room.

```
======== send from Conversations =============
06-18 08:58:49.734 31293-31347/eu.siacs.conversations D/conversations: update unread count to 1
06-18 08:58:49.784 31293-31347/eu.siacs.conversations D/conversations: hawk@atalk.sytes.net: suppressing notification because turned off
06-18 08:58:49.844 31293-31293/eu.siacs.conversations D/conversations: update unread count to 0
06-18 09:00:21.634 31293-6337/eu.siacs.conversations D/conversations: retrieve file size. interactive:false
06-18 09:00:21.634 31293-6337/eu.siacs.conversations D/conversations: url: https://atalk.sytes.net:5443/upload/atalk.sytes.net/160ce91b31fe9fc0d13bad06ed50e0aacccbc854/CmJJZltvmG8Cvl9yAbOOiGSIKrE1rvCTD0oOHfXF/hLDGNe5HSBCZY2dSJQQ67Q.png
06-18 09:00:21.644 31293-6337/eu.siacs.conversations I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
06-18 09:00:21.654 31293-6337/eu.siacs.conversations I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
06-18 09:00:21.784 31293-6355/eu.siacs.conversations I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
06-18 09:00:21.784 31293-6355/eu.siacs.conversations I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false

======== send from aTalk =============
06-18 09:00:21.844 31293-6355/eu.siacs.conversations I/CameraExif: Orientation not found
06-18 09:00:21.864 13006-13968/? D/ActivityManager: bindService callerProcessName:eu.siacs.conversations, calleePkgName: com.android.providers.media, action: android.media.IMediaScannerService
06-18 09:00:22.224 31293-31354/eu.siacs.conversations I/CameraExif: Orientation not found
```
