### ISSUE TITLE
do we have just active ( talked before user list ? )

### ISSUE THREAD

**Issue by vampiebar** [cmeng-git/atalk-android#153]
We have users when we added.. ( can we seperate user list ( which we added but not talked before ) will only be seen on users list but not chat list ) is there any distinguish ?

**Comment by cmeng-git** [comment]
No, currently aTalk does not provide an UI just to display active chat sessions. Each active chat session is highlighted (bold) in the respective contact list or group chat list view.

By the way, may I know what is the size of the contact list?

**Comment by vampiebar** [comment]
size of list can be 300+ lower than 1000

**Comment by vampiebar** [comment]
can we design active sessions ? from xmpp ?

**Comment by cmeng-git** [comment]
It is not an XMPP protocol, but an UI feature.

Look like you have a big number of contacts.
Would you mind to describe how and where exactly you use aTalk.
I am interested to know the reason why an aTalk user has such a big group of contacts.

**Comment by vampiebar** [comment]
Internal company usage in doha..

**Comment by cmeng-git** [comment]
Release aTalk v2.3.2 has added in the 'Recent Conversations' UI. It is the third page on main page slider.

**Comment by vampiebar** [comment]
Thanks for the information and effort...
