### ISSUE TITLE
Can we have encrypted file storage?

### ISSUE THREAD

**Issue by vampiebar** [cmeng-git/atalk-android#155]
What is the easiest way to encrypt media files and reopen it with the program?
We want to secure files on disk

**Comment by cmeng-git** [comment]
aTalk does not provide such support. You have to do it outside aTalk application.

**Comment by vampiebar** [comment]
What is the easiest way to implement media files into SQLITE byte 
or uuencoded string.. I want to crypt media into sqlite cipher..

**Comment by cmeng-git** [comment]
Sorry, this is not a forum to discuss the implementation. you need google online and find out yourslef.
