### ISSUE TITLE
ping time 240 default.. how to keep alive

### ISSUE THREAD

**Issue by vampiebar** [cmeng-git/atalk-android#156]
Is there a way for app when focus ( make up front ) or background force to keep alive.. such as sending login trial / connection request if not connected?
or is there any parameters?

**Comment by cmeng-git** [comment]
If you are referring to aTalk, you can find all the info on aTalk online help i.e.:
https://cmeng-git.github.io/


[20180710] XEP-0198:Stream Management and ReConnection Manager
[20181015] Network Keep Alive - Ping Interval Optimization
