### ISSUE TITLE
Offline file transfer

### ISSUE THREAD

**Issue by vampiebar** [cmeng-git/atalk-android#157]
https://xmpp.org/extensions/xep-0363.html is supported?
Support HTTP File Upload for file sharing with offline contact and in group chat
how can we support offline file transfer?

I think XMPP does not support it.. and workaround is HTTP file upload.. is your client support this?

**Comment by cmeng-git** [comment]
Please see online help:
[[20190902] aTalk Fault-Tolerance File Sharing Implementation & Enhancements](https://cmeng-git.github.io/faq.html#feature_05)
