### ISSUE TITLE
the user account fails to connect to the Openfire server in the new version 2.3.1 

### ISSUE THREAD

**Issue by ashfik2000** [cmeng-git/atalk-android#158]
![image](https://user-images.githubusercontent.com/66199076/87559990-43fc1780-c6bb-11ea-9c95-2d5c9ae0760d.png)

note: version 2.3.0 works fine

**Comment by cmeng-git** [comment]
v2.3.1 uses smack library 4.4.0-alpha5. Are you able to provide me a test account on your server for testing; my test server does not use 'SSL Certificate Authentication'

**Comment by cmeng-git** [comment]
Sorry, I miss interpreted your screenshots, thinking that your are using the SSL client certificate for login.

I have verified and confirmed that the latest v2.3.1 release, there is no problem with the login.

The error message indicates that your server is not responding to the login request. Kindly check your server. If you are still facing the problem, please send me the debug log.

**Comment by cmeng-git** [comment]
Yes, there is an error in login when the server override option is enabled.
Has fixed and will be in next release.

**Comment by cmeng-git** [comment]
Release aTalk v2.3.2 with the fix. Please verify.
