### ISSUE TITLE
the user account does not login automatically in ver 2.3.3

### ISSUE THREAD

**Issue by ashfik2000** [cmeng-git/atalk-android#161]
if you close aTalk and reopen it, the user account does not login automatically in ver 2.3.3 and you must choose sign in from menu or wait for the 240 seconds of ping interval. this means that it is not working in the background within this period.

Also, in case of performing a jingle call and the receiver person cancels the call the vibration is still working until the user presses the mobile power button (this is happening only with  jingle call and the legacy call works fine).

**Comment by cmeng-git** [comment]
> if you \<close> aTalk and reopen it, the user account does not login automatically in ver 2.3.3 and you must choose sign in from menu or wait for the 240 seconds of ping interval. this means that it is not working in the background within this period.

Please explain what you mean by \<close>. If you mean \<Exit>,  aTalk remembers the last login state selected by user. If the state was 'sign out', then user will have to manually select 'sign in' to login again when he enter aTalk.
If aTalk was signed in before exit or press \<back key>, aTalk will sign in automatically when you open aTalk again.
I have verified and confirmed aTalk works as expected.

> Also, in case of performing a jingle call and the receiver person cancels the call the vibration is still working until the user presses the mobile power button (this is happening only with jingle call and the legacy call works fine).

Will take a look.

**Comment by ashfik2000** [comment]
> Please explain what you mean by <close>. If you mean <Exit>, aTalk remembers the last login state selected by user. If the state was 'sign out', then user will have to manually select 'sign in' to login again when he enter aTalk.
> If aTalk was signed in before exit or press <back key>, aTalk will sign in automatically when you open aTalk again.
> I have verified and confirmed aTalk works as expected.

i checked again closing the aTalk using <Exit> from the menu or pressing <X> from the app title bar in either choice the program is not connecting automatically  when reopening (like previous versions)  noticing that press <back key> is not closing aTalk app but hiding it back with other current opened programs

**Comment by ashfik2000** [comment]
> Please explain what you mean by <close>. If you mean <Exit>, aTalk remembers the last login state selected by user. If the state was 'sign out', then user will have to manually select 'sign in' to login again when he enter aTalk.
> If aTalk was signed in before exit or press <back key>, aTalk will sign in automatically when you open aTalk again.
> I have verified and confirmed aTalk works as expected.

i checked again closing the aTalk using "Exit" from the menu or pressing" X" icon from the app title bar in either choice the program is not connecting automatically  when reopening (like previous versions)  noticing that pressing back key is not closing aTalk app but hiding it back with other current opened programs

**Comment by cmeng-git** [comment]
Just cannot reproduce the problem on my side. Please send me the full log. Do not trim any info.

**Comment by ashfik2000** [comment]
I just added the accidentally deleted code to  ver 2.3.2  and the above problem is solved in ver 2.3.2 
So I think there is a problem in another added code in  ver 2.3.3

**_the added code:
1- inside MclStorageManager.java :_**
 public static void initMCLDataBase(SQLiteDatabase db)
    {
        ContentValues mclValues = new ContentValues();
        // dummy account for root group
        String accNodeName = "acc" + Long.toString(System.currentTimeMillis());

        mclValues.put(MetaContactGroup.ACCOUNT_UUID, accNodeName);
        mclValues.put(MetaContactGroup.PARENT_PROTO_GROUP_UID, ContactGroup.ROOT_NAME);
        mclValues.put(MetaContactGroup.MC_GROUP_UID, ContactGroup.ROOT_GROUP_UID);
        mclValues.put(MetaContactGroup.PROTO_GROUP_UID, ContactGroup.ROOT_PROTO_GROUP_UID);
        mclValues.put(MetaContactGroup.MC_GROUP_NAME, ContactGroup.ROOT_GROUP_NAME);
        db.insert(MetaContactGroup.TABLE_NAME, null, mclValues);
}

**_2- DatabaseBackend.java :_**
import net.java.sip.communicator.impl.contactlist.MclStorageManager; 
MclStorageManager.initMCLDataBase(db);

**Comment by cmeng-git** [comment]
I just performed another new installation of aTalk v2.3.3 on AVD API-21; after a complete aTalk directory purged,  cleared cache, cleared data and uninstalled.  Still I am unable to reproduce your observed problem. aTalk is working as expected.

I really need you to send me the debug log on your device for me to understand the problem.

Note: If you are interested, there is a ReleaseNote.txt file in project aTalk directory. It contains a detailed description of all the changes for each aTalk version.

**Comment by cmeng-git** [comment]
Just released aTalk v2.3.4 to fix vibrator problem.

As for your first reported problem, I have not received any debug log to substantiate your observation.
I shall considered it is NTF and closed the issue.
