### ISSUE TITLE
Add translation for pt_BR, pls

### ISSUE THREAD

**Issue by aevw** [cmeng-git/atalk-android#162]
Hi aTalk,

Please add translation for aTalk in [pt_BR](https://github.com/aevw/RD-pt_BR/blob/master/at-strings-pt_BR.xml).

Thanks

**Comment by cmeng-git** [comment]
Thanks for your contribution.  Has included the Português (Brasil) language for next aTalk release.

**Comment by cmeng-git** [comment]
Has released the request in aTalk v2.4.0
