### ISSUE TITLE
Unsupported path when sending an image 

### ISSUE THREAD

**Issue by Folaht** [cmeng-git/atalk-android#164]
An online friend of mine using atalk recieves this message when I send an image link.
I can't replicate this myself.

**Comment by cmeng-git** [comment]
What is your friend device android OS version?

"Unsupported path" is runtime error returns by android OS.
https://stackoverflow.com/questions/58379543/cant-create-directory-in-android-10

Just in case, please ensure your friend has granted the Storage permission to aTalk.

**Comment by cmeng-git** [comment]
I have made the recommend changes as per the link in aTalk v2.4.0 release.
Please check and let me know if your friend still facing the problem.

**Comment by Folaht** [comment]
Storage permission to aTalk had been granted.
She's still getting 'Unsupported path storage' and since I use Gajim,
I can confirm that she's using version 2.4.0 from her contact info.

**Comment by cmeng-git** [comment]
Look like android-Q enforces and disallowed app to access to /storage/emulated/0. The proposed fix in the previous link is no longer a solution. aTalk needs to release a new version to resolve the problem for android-Q device.
https://stackoverflow.com/questions/58379543/cant-create-directory-in-android-10

     * @see #getExternalStorageState()
     * @see #isExternalStorageRemovable()
     * @deprecated To improve user privacy, direct access to shared/external
     *             storage devices is deprecated. When an app targets
     *             {@link android.os.Build.VERSION_CODES#Q}, the path returned
     *             from this method is no longer directly accessible to apps.
     *             Apps can continue to access content stored on shared/external
     *             storage by migrating to alternatives such as
     *             {@link Context#getExternalFilesDir(String)},
     *             {@link MediaStore}, or {@link Intent#ACTION_OPEN_DOCUMENT}.
     */
    @Deprecated
    public static File getExternalStorageDirectory() {
        throwIfUserRequired();
        return sCurrentUser.getExternalDirs()[0];
    }

**Comment by Folaht** [comment]
She just told me she is using android version 10.

**Comment by cmeng-git** [comment]
Just released aTalk v2.4.1. Please verify it fixes the 'unsupported path' problem

**Comment by cmeng-git** [comment]
Sorry, the release was blocked by android team due to some errors in aTalk Store Listing. I was working with them for the last few days to get it clear to release. Just received the confirmation from android team, it has cleared the blockage and is now available for update.

**Comment by cmeng-git** [comment]
Issue assumed resolved with not user update

**Comment by Folaht** [comment]
Issue resolved.

**Comment by cmeng-git** [comment]
Thanks for your update. Glade to know it has been resolved.
