### ISSUE TITLE
Trouble finding the permission settings once having an account.

### ISSUE THREAD

**Issue by Folaht** [cmeng-git/atalk-android#166]
Maybe they are in the advanced settings or connection settings that freezes up the application,
but I would expect a "Permission settings" option in "Settings" or something along that line.

**Comment by cmeng-git** [comment]
Please see online help:
https://cmeng-git.github.io/faq.html
The online help is also can be accessed from the main menu.

Android Battery Optimization & Run-time Permissions Request { Content }
