### ISSUE TITLE
A display issue

### ISSUE THREAD

**Issue by franklinbill** [cmeng-git/atalk-android#171]
Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure, in the first page, the button and the following text overlap each other. This may be an adaptation problem. I suspect it is because **display and font size** are set to large (mainly due to **display size**).
I hope that the page can be set to scroll, so that the problem caused by the display size of large can be solved.
App version is 2.4.3, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **_font size and display size are the largest ! ! !_**, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!
<img width="449" alt="bug-atalk" src="https://user-images.githubusercontent.com/18572115/103147210-2b297f00-478e-11eb-9d48-8494fb7673ad.png">

**Comment by cmeng-git** [comment]
aTalk UI is designed based on a screen resolution of 1080x1920 with English as a default language; and with the device default resolution density. If the user changes/scales the system font size using the Accessibility, one will find a lot of the aTalk UI's are not displaying correctly, as aTalk was never design for such uses. Below is the actual display with the system default font setting.

If this is the only problem you are facing, you can set the aTalk requested permissions via the APP Info, which will produce the same result.

![image](https://user-images.githubusercontent.com/7959606/103147338-46e15500-478f-11eb-921c-caaa0cd61299.png)

**Comment by cmeng-git** [comment]
aTalk UI is designed based on a screen resolution of 1080x1920 with English as a default language; and with the device default resolution density. aTalk was never designed to support accessibility option with large font.
