### ISSUE TITLE
can not rename package

### ISSUE THREAD

**Issue by ejabberedatalk** [cmeng-git/atalk-android#172]
Hi,

I renamed package in android studio and updated applicationId and then did invalidating cache, cleaning, rebuilding etc multiple times, but I am getting many different errors. 

Can you please try renaming package from your side and please tell me how we can do it for this aTalk app, I think this is issue related to aTalk only because I have renamed many apps successfully in past, never faced so many errors. 

I tried to change only from "atalk" to "cewme", everything is same

**Comment by cmeng-git** [comment]
You should refer your problem to the AS development team. The problem has little to do with aTalk app itself, I am unable to give you any assistance on this.
