### ISSUE TITLE
Harmony OS support?

### ISSUE THREAD

**Issue by Folaht** [cmeng-git/atalk-android#174]
Will atalk run on Harmony OS anytime soon?

**Comment by cmeng-git** [comment]
Actually I do not own any Huawei device for testing. My understanding is that Harmony OS can run android apps without changes.

I do not mind port aTalk to Harmony OS if need to, but I must get myself a device first. No sure if Huawei is willing to provide a complementary phone for aTalk development.

**Comment by cmeng-git** [comment]
Attempted, but found the latest harmonyOS 4.x does not support java source coding anymore; this has made aTalk porting to harmonyOs near impossible.
