### ISSUE TITLE
It seems to not work on lineage and pine64.

### ISSUE THREAD

**Issue by ecxod** [cmeng-git/atalk-android#177]
It seems to not work on lineage and pine64.
It seems to log in, so for example it recognizes a bad password, but after login nothing happens. It shows the account as offline and no communication even unencrypted is possible. Prolly it depends on some google packages that nobody needs.

**Comment by cmeng-git** [comment]
aTalk is designed to work on android OS, and was never tested on open OS. I will take a look if you would send me the aTalk debug log.

Please refer to the online help for more info.
https://cmeng-git.github.io/atalk/faq.html
