### ISSUE TITLE
GitHub Diff files limitation

### ISSUE THREAD

**Issue by ashfik2000** [cmeng-git/atalk-android#178]
when i browse version 2.6.1 commit from this url:
https://github.com/cmeng-git/atalk-android/commit/bb4d6702ea954fac350698eb63e5fe027015620d

the following error appears due to GitHub limitations:
**Showing 34,077 changed files with 972,699 additions and 662,704 deletions.
The diff you're trying to view is too large. We only load the first 3000 changed files.**

is there a way to view all changes or at least excluding jni files changes and view orher changes in aTalk files

**Comment by cmeng-git** [comment]
This error is generated by github on displaying the max number of differences. You need to refer to github for help.

**Comment by ashfik2000** [comment]
I solved the issue by installing GitHub Desktop software on my pc . 
Best Regards

**Comment by cmeng-git** [comment]
Thanks for the info.
