### ISSUE TITLE
Feature Request <3

### ISSUE THREAD

**Issue by vboxpro** [cmeng-git/atalk-android#18]
1. Add Emoji pack for atalk for basic emotions 
https://getemoji.com
2. also Sticker Pack if possible. 
https://chatsticker.com/top?page=2&term=
 (add facility for users to add their own emoji/sticker themselves)

love your app <3 <3

**Comment by cmeng-git** [comment]
aTalk has no intention to restrict users in using other xmpp clients for communication; so emoji consistency in aTalk chat does not arise in its initial design goal. There are also ongoing effort to standardize emoji across all mobile devices. At least for now, aTalk would not want to spent time to add user option to have user own emoji. There are other more important features that require my time.

**Comment by cmeng-git** [comment]
The latest release of aTalk v1.5.2 has added support for Stickers, Bitmoji and Emoji rich content sharing using Google Gboard keybard. Please go the the following site for more info:

[Stickers, Bitmoji and Emoji rich content sharing](http://atalk.sytes.net/faq.html#feature_04)

**Comment by vboxpro** [comment]
Thanks
 but like something as Telegram and other messenger apps. it has default emoji list for common use and additionally sticker packs. 
    just its very easy to use than open from keyboard manually and most android devices has manufacture's keyboard as usual ex: Huawei
