### ISSUE TITLE
no menu item "Send my GPS-Location"

### ISSUE THREAD

**Issue by tengel** [cmeng-git/atalk-android#181]
I can't find a menu item to send my GPS location. I guess it should be in the chat window menu, which contains the items Intive, Audio call, Video call, Erase this contact history, OTR Sessions. Does this feature not exist anymore? The F-Droid apk seems not to require any location permission.

aTalk Version 2.6.2 (F-Droid)
Android 7.1.2 (LineageOS 14.1)

**Comment by cmeng-git** [comment]
This feature is only available on android playstore version.

**Comment by cmeng-git** [comment]
Option already implemented in google playstore version

**Comment by cmeng-git** [comment]
The send GPS location option is now available in fdroid v3.0.2 release

**Comment by tengel** [comment]
Is working. Thank You.
