### ISSUE TITLE
Screen with overlapped controls

### ISSUE THREAD

**Issue by pirujo** [cmeng-git/atalk-android#189]
Hello.

There are a screen (permissions) with overlapped controls on it. I'm attaching a screenshot.

![Screenshot_20220306-101758](https://user-images.githubusercontent.com/45567259/156918776-4e57d62d-e2ca-4c51-83df-c1930116d9ad.png)

**Comment by cmeng-git** [comment]
During aTalk design and testing, it is based on  a minimum display size of a HD resolution, and with English text. In the case of your android device, it uses a part of the valuable display area for the soft buttons. You need to set your device to auto hide the soft-button, until user slides upward to reveal the soft-button. 

![image](https://user-images.githubusercontent.com/7959606/156970471-709ffb13-c4c7-4242-8cee-014148722705.png)
