### ISSUE TITLE
Host doap file for client represenation on xmpp.org

### ISSUE THREAD

**Issue by Echolon** [cmeng-git/atalk-android#197]
Hi,

to better advertise your client on https://xmpp.org/software/clients/ I would like to recommend to host a doap file.

Find a good example: https://github.com/conversejs/converse.js/blob/master/conversejs.doap
Entry here: https://github.com/xsf/xmpp.org/blob/master/data/clients.json#L327

**Comment by cmeng-git** [comment]
Would you like to help generate the file based on info in the README.md?

**Comment by Echolon** [comment]
@cmeng-git unfortunately I cannot, but you have a basic file available in the first post. You can do it step by step. Maybe you can ask for support in your user community?

**Comment by butyoutried** [comment]
https://xmpp.org/software/atalk/

This issue can be closed now :)

**Comment by cmeng-git** [comment]
add aTalk.doap file
