### ISSUE TITLE
Translate to spanish

### ISSUE THREAD

**Issue by susobaco** [cmeng-git/atalk-android#2]
Hello, what files should I choose for the Spanish translation? (and probably the other languages of Spain)

**Comment by cmeng-git** [comment]
Currently atalk-android supports only English.  There are a lot more work to do within the code to support other languages. The actual language translation is to covert all the strings in values/string.xml to the required languages.

**Comment by cmeng-git** [comment]
I believe they are lines of code and need not to be translated.

On April 19, 2018 3:21:21 PM GMT+08:00, "Suso Comesaña" <notifications@github.com> wrote:
>Hi, I'm translating the strings and I have a question. Entries where
>there is no separation between words ( Example:
>pref.cat.security.general pref_key_ProxyEnable ) must also be
>translated, or are they lines of code?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/cmeng-git/atalk-android/issues/2#issuecomment-382636457

--
Send from Android using XryptoMail

**Comment by cmeng-git** [comment]
Integrated since 1.2.5
