### ISSUE TITLE
Fdroid release: aTalk 3.3.0 targeted for android API-34 requires pre-compiled smack jar libraries

### ISSUE THREAD

**Issue by cmeng-git** [cmeng-git/atalk-android#207]
In order to support aTalk release for android API-34, changes in SDE are required as below:
- Upgrade Android Studio to Giraffe - but with Gradle-JDK using jdk-15;
  butterknife-compiler:10.2.3 is required for PermissionsActivity, but only compatible with jdk-15 max
- Need  jarjar-gradle from github master i.e. '9a7eca7' (1.1.1)
- Require gradle-8.2-bin.zip and pre-compiled smack jars (see below)
- Use 'com.android.tools.build:gradle:7.4.2' and 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.22'

Due to the way gradle version > 6.9 handling of jarjar function, it does not support 'destinationName' in the generation of jar file. Instead it uses a random generated filename. This breaks the current dependency references defined for other smack libraries.

Due to the above limitation, aTalk v3.3.0 build needs to rely on three pre-compiled smack jar libraries i.e. 
a. smack-experimental.jar
b. smack-extensions.jar
c. smack-omemo.jar

These smack libraries are from previous aTalk v3.2.4 release, build based on maven repository releases.
Unless Fdroid can waive these deviations, else aTalk v3.3.0 is temporary unavailable for Fdroid release.

**Comment by cmeng-git** [comment]
aTalk v3.3.1 (20240112) release has resolved all the above issues and is ready for fDroid build.

**Comment by linsui** [comment]
Thanks, updated.

**Comment by cmeng-git** [comment]
Issue resolved

**Comment by cmeng-git** [comment]
Feedback from aTalk users that both 3.3.0/3.3.1 aTalk releases have problem of user login; This problem does not happen in adb debug version. Just updated aTalk to v3.3.2. Please release asap.

**Comment by linsui** [comment]
As always it will be updated automatically but the build cycle may take few days...
