### ISSUE TITLE
but report: On Samsung devices aTalk doesn't sign in

### ISSUE THREAD

**Issue by firefish475** [cmeng-git/atalk-android#209]
[2024-01-23@21.25.32-logs.zip](https://github.com/cmeng-git/atalk-android/files/14029540/2024-01-23%4021.25.32-logs.zip)

Info below can help developer fix the problem:

1. What was the last thing you did before the problem happen?

Just starting the app.

2. What was the problem that you see, include a snapshot of the display if available?

The account configure does not sign in. It stays offline and no buddy list occurs.

3. Can you or how to reproduce the problem?

The problem occurs every time I log in. It isn't possible to use atalk due to that. This is the case with version 3.3.1 from F-Droid and from Google Playstore. From F-Droid I could install version 3.2.4 and it works. It signs in and the buddy list is displayed.

Just sending this bug report again because I cannot find it in any outbox.

**Comment by firefish475** [comment]
I open this bug report because I could not send email to cmeng.gm@gmail.com for some unknown reason. My mail isp just gives me the error could not send mail.

**Comment by cmeng-git** [comment]
Just realise that aTalk built during system debug, and the built for playstore official release has completely two different behaviour. aTalk release version has problem, has lead to user unable to login. Problem under investigation.

**Comment by cmeng-git** [comment]
Just release aTalk 3.3.2, please try out and see if this has fixed the problem.
Note: JingleFile send still facing problem. awaiting AS team feedback.

**Comment by firefish475** [comment]
Version 3.3.2 logs in ok on my devices.

**Comment by cmeng-git** [comment]
Thanks for your update.

**Comment by firefish475** [comment]
File sending indeed fails. sth like "must not be null and must exist"

**Comment by cmeng-git** [comment]
The JingleFile sent is working correctly without problem in system testing via Debug | ADB install in Android Studio. 

The problem only happen in app compiled for playstore release, it throws AbstractMethodError during file sending.
I have raised the issue with the Android Studio development team for action.
Refer to the link for more detail: https://issuetracker.google.com/issues/321988935

**Comment by cmeng-git** [comment]
For aTalk v3.3.3:
Temporary disable 'Jingle Outgoing File Offer', use only HTTP file upload instead to allow file transfer on aTalk
