### ISSUE TITLE
Modern UI Like MOxxy 

### ISSUE THREAD

**Issue by methuselahin** [cmeng-git/atalk-android#212]
https://codeberg.org/moxxy/moxxy 
the UI of the app is very ancient look alike. The basic functionality is working but to ask the contacts to be available on the same we need to have good ui like moxxy and conversations

**Comment by cmeng-git** [comment]
To update the UI, is likely require 3~4 man of various expertise, and a 1 year effort. aTalk is a 1-man development team,
and the main aim is to develop a simple and reliable app for use.
Your request is not achievable, unless you would like to form a team to contribute. I have to decline your request.
