### ISSUE TITLE
[Feature request]: provide APK in GitHub releases

### ISSUE THREAD

**Issue by Sami32** [cmeng-git/atalk-android#216]
Instead of relying on F-Droid we could directly download it with Obtainium or similar Apps updater.

**Comment by cmeng-git** [comment]
android does not allow release of apk with API_KEY into any public domain. 
Also aTalk cannot not support auto update with this type of release; user has to check manually at regular interval for any new update.

**Comment by Sami32** [comment]
Providing your releases on F-Droid is OK, but not on GitHub?

Do you mean that your Apps is relying on Google Play services?

Obtainium and similar Apps handle auto updates pretty well.

**Comment by cmeng-git** [comment]
Providing your releases on F-Droid is OK, but not on GitHub?
* No comment. Actual Fdroid release does not required the API_Key, but get added in by AS build. Raised the issue with android development team, but no action taken so far.

https://stackoverflow.com/questions/52784989/how-do-i-handle-a-secret-api-key-when-i-push-to-github-so-that-my-project-is-sti
* When aTalk check in the Fdroid apk into the github directory, google immediately send an email to alert me not to include api_key in public domain.

Do you mean that your Apps is relying on Google Play services?
* Yes, if you meant the auto update. I suppose Fdroid repository also support this feature.

Obtainium and similar Apps handle auto updates pretty well.
* aTalk has already implemented auto-update feature, but it is only for DEBUG release. Fdroid users do not want this feature to be included in the Fdroid RELEASE version.

Please note apk if released into github will contain a different signature; it is not compatible with apk released by Fdroid. User cannot install one over the other for any update. This will confuse user.

As the aTalk Fdroid release is already handled by Fdroid repository, I cannot see any good reason to release another Fdroid release in github with a different signature.
