### ISSUE TITLE
Android 7 turn server is not saved

### ISSUE THREAD

**Issue by feroom** [cmeng-git/atalk-android#22]
Android 7 (Motorola G5 Plus, clean Android system)
I am trying to add STUN (TURN) server IP, the account setting is not saved)
Can you advise something?

**Comment by weiss** [comment]
For me (Android 7, Moto G5 Plus as well), saving settings fails if I use aTalk's back button (at the top left) but it works if I use Android's back button.

**Comment by cmeng-git** [comment]
OK, now I understand the problem.
current aTalk implementation treats the up navigator i.e. top left corner "\<" as Home key and will ESC/returns to the main activity i.e. Contact List. 

However when there are account setting changes. aTalk needs to perform a re-login process to ensure the new settings take effect in the current session. This login process is performed only when user press back key until the menu returns to the first account info edit menu. This is also where all the account setting changes are being saved to the persistent database. All other sub-menu save process only update changes in memory space including stun settings.

For the aTalk v1.5.6 release, user has to press the back keys to ensure any changes made are properly saved. I need to review the current aTalk implementation, and see if there is a need to change;  will get any changes included in the next release.
