### ISSUE TITLE
Building Instruction or Wiki

### ISSUE THREAD

**Issue by ariebrainware** [cmeng-git/atalk-android#26]
Please provide more information about how to build this project also SDK requirement and etc.

Thanks

**Comment by cmeng-git** [comment]
It is compiled using Android Studio 3.2 running on Ubuntu 18.04. Just download the source and build, As will tell you what SDK is required.

**Comment by ariebrainware** [comment]
Is there any specific reason why we need to use Ubuntu? is that oke to use debian also?

**Comment by cmeng-git** [comment]
it is only a personally preference. However each OS has it its own requirements in setting up the environment and tools for software development.
