### ISSUE TITLE
[Enhancement] - Uninterrupted Video Calling

### ISSUE THREAD

**Issue by hub-ch** [cmeng-git/atalk-android#27]
`checked: aTalk 1.6.2`

Current aTalk application during video call, if tries to send message then video call pause until move back to call window. (personally that makes bored to use the app)
      below're resources, may consider improve within upcoming releases. <3 ^_^

----------

**Request - 1 - Important**

 [sample]
Skype - android
https://play.google.com/store/apps/details?id=com.skype.raider&hl=en

on android app during video call even completely moved to chat window or for other task from video call window but another end user still can see him/ her without any interruption[no pause]
   you can check with another skype windows http://go.skype.com/skype.download  or mobile device

-----------

**Request - 2**
additional improvement,

[sample]
Hangout - android
https://play.google.com/store/apps/details?id=com.google.android.talk&hl=en_US

screenshot - https://prntscr.com/luw146
  enhance for appear small chat window on the top for reply during video call when another end user send new message (it helps to not move to chat window always) however **_Request - 1_** required (Important)
  note: hangout pause video call same as current aTalk if moves to chat window for send message. that sample for request - 2

------------

kindly try to have smooth UI, entire screen video call for aTalk as modern chat apps similar,
 *skype.com - android 
*wire.com - android (opensource) https://github.com/wireapp/wire-android (sample for UI)
               it'll be great but please care about our phone battery :D

Thanks <3 ^_^

**Comment by hub-ch** [comment]
Closes #27

**Comment by cmeng-git** [comment]
aTalk requires a major architecture change to allow both chat and video to happen simultaneously. I am weighting the risk of the changes against the number of users would use this feature. I would hold back such major change at this point, as there are other more important thing I need to consider.

**Comment by hub-ch** [comment]
ok ^_^ get back to this at convenient time^^
also i'll not forget to link if found any other suitable opensource resources and reopen this issue.

i know its important to improve security related thing but also most people attract or use due smart UI/ emoticons/ emojis etc and other facilities that we see on most popular communication platform even data collections, no encryption. 
and there many privacy, security optimized opensource projects like this but its hard to make normal person, friend, family to use them (that not in IT or not aware about privacy, security). just you can see that on your daily life than i say.
    take my idea and continue without affect to your main tasks.
