### ISSUE TITLE
Feature request: Show photos in the conversation

### ISSUE THREAD

**Issue by codedivine** [cmeng-git/atalk-android#28]
Right now sending photos and videos can be done using the send attachment option. But unlike other mobile messaging apps,  there is no special support for viewing photos and videos right within the app in the conversation view.

**Comment by cmeng-git** [comment]
Features already supported. Just tap on the received file icon in the conversation chat item. aTalk will launch your default app that is assigned for the selected file type.

Note that your android device must have the appropriate app that support the viewing or playback of the media type installed.

**Comment by codedivine** [comment]
I meant being able to view it within the app, without having to open an external application.

**Comment by cmeng-git** [comment]
This implementation requires aTalk to have all the UI designed for all received file types. Look like it is impossible app to support such request. Any good reason why you must open the file within the chat window.
