### ISSUE TITLE
XEPs support page with version

### ISSUE THREAD

**Issue by Neustradamus** [cmeng-git/atalk-android#3]
It is possible to have a XEPs support page with version?
https://github.com/cmeng-git/atalk-android/blob/master/README.md

Examples:
- https://metronome.im/supported-xeps-list
- https://trac.gajim.org/wiki/GajimXEPSupport
- https://github.com/jappix/jappix/blob/master/PROTOCOL.md

**Comment by cmeng-git** [comment]
I have no intention to do it as least for now. It takes too much effort to check and verify version against the actual code implementation. In all cases, aTalk will always try to adhere to the latest requirements unless for all old device compatibility.

**Comment by Neustradamus** [comment]
@cmeng-git: Any news about support?

**Comment by cmeng-git** [comment]
There is no change to my earlier decision.
