### ISSUE TITLE
OMEMO issue

### ISSUE THREAD

**Issue by alexandre1985** [cmeng-git/atalk-android#32]
I can't establish omemo encryption with this program.
I have installed Conversations first, and everything worked.
Then I notice that conversations didn't had videocall so I found atalk.
With atalk the video chat works (tested to another atalk client) but the omemo text chat encyption is not working.
OTR and unencrypted chat is working though.

**Comment by cmeng-git** [comment]
Please send the atalk debug log for investigation, refer to the following site for more info:
https://atalk.sytes.net/atalk/faq.html

Refer to the discussion link if your server is prosody
https://github.com/cmeng-git/atalk-android/issues/31#issuecomment-476927987

**Comment by cmeng-git** [comment]
Based on mail conversations:

trashserver.net server uses prosody xmpp services (version unknown), the latest release 0.11.2 (released: 2019-01-09) has been verified  to deviate from standard xmpp implementation. Please refer to the following link for more information:
https://github.com/cmeng-git/atalk-android/issues/31#issuecomment-476927987

FYI:
a. conversations always enable the omemo option without performing either server or jid entities omemo support verification.
b. aTalk checks both server and jid entities to ensure both can support omemo before the option is enabled.
The latest prosody xmpp service release 0.11.2 (released: 2019-01-09) failed server omemo support validation in aTalk v1.8.1 omemo chat, hence the omemo option is being disabled.
Will provide alternate verification to enable omemo chat in the upcoming aTalk 1.8.2 release; and continuous monitor its effect on proper operation of the omemo chat.

**Comment by alexandre1985** [comment]
Thank you Cmeng.
If I have OMEMO support with my account and your client, I will definitly choose your client over Conversations.
I find your client superior.

Hope too see that implemented and thanks for your feedback

**Comment by cmeng-git** [comment]
Just release aTalk v1.8.2 to support Prosody xmpp implementation deviations.
Please feedback if you still see problem.

**Comment by alexandre1985** [comment]
If tested now and is working great.

When Im on a video call if I press the go to message button (the far left button) while im on a video call, my phone vibrates and beeps without no stopping. May that needs fixing.

Other suggestion is why not have atalk on fdroid also (not only on play store)?

Many thanks good man

-------- Mensagem Original --------
Ativo 24 de abr de 2019 03:15, Eng ChongMeng escreveu:

**Comment by cmeng-git** [comment]
See see below for F-droid release version:
https://github.com/cmeng-git/atalk-android/issues/1

> When Im on a video call if I press the go to message button (the far left button) while im on a video call, my phone vibrates and beeps without no stopping. May that needs fixing.

From my side, I do not see this problem on all my testings.
Can you check the aTalk notifications in settings? Let me know if there is any difference from the attached image.
Set Call Notification to silent if different. Exit aTalk and try again to see if fixes the problem.

What is your andorid device and its OS version?

![image](https://user-images.githubusercontent.com/7959606/56703458-7e3a6b80-673b-11e9-9331-e684a87a902c.png)

**Comment by alexandre1985** [comment]
I have call notification with screen popup and sound.
Also general notification I have it turned off.

Will test this again, when the xmpp server that im using is online again

-------- Mensagem Original --------
Ativo 25 de abr de 2019 02:27, Eng ChongMeng escreveu:

**Comment by cmeng-git** [comment]
The App notifications are the new notification channels enforced and controlled by android-OS. All notifications from app must send via one of these main channels. The 'aTalk Call Notification Panel' is sent via the android 'Call Notification' channel. You should keep the default channel settings from aTalk i.e. enabled with silent for all these main channels.
If you setup alerts/vibrates on these main channels, they get added into the aTalk event actions, and may hear double alerts for incoming call etc.

aTalk has its own much more defined Notifications actions in [settings | Events]; use this to set the required actions for each event as shown below. Look like I need to includes this in my FAQ site.

![image](https://user-images.githubusercontent.com/7959606/56843276-19b11500-68d1-11e9-872e-a907f2263378.png)

**Comment by alexandre1985** [comment]
Ok.
Now that i put all notifications the way they were i have one issue.
The atalk icon is always showing on my android status bar. I want to get rid of this icon.
What is the correct way of doing this?
One way would be to disable atalk general notifications...
-------- Mensagem Original --------
Ativo 27 de abr de 2019 02:53, Eng ChongMeng escreveu:

**Comment by alexandre1985** [comment]
The notification is the one saying that atalk is oneline

**Comment by cmeng-git** [comment]
Uncheck the [Setting... | Display aTalk icon] option.

**Comment by alexandre1985** [comment]
Thank you @cmeng-git
