### ISSUE TITLE
jitsi-desktop

### ISSUE THREAD

**Issue by testbird** [cmeng-git/atalk-android#34]
Is jitsi-desktop still available from jitsi.org at all?

(I guess atalk is not compatible with jitsi meet.)

**Comment by cmeng-git** [comment]
My observation was that jitsi-desktop support has reduced to minimum after jitsi was acquired by Atlassian Pty Ltd. May be jitsi team member would like to comment on this.

Jitsi-meet uses webrtc service i.e. web based services, whereas aTalk implementation uses xmpp protocol. Jitsi-meet and aTalk are no compatible.

**Comment by testbird** [comment]
Thanks for sharing your observation. So no wonder I didn't find a working direct download for a .deb file at https://desktop.jitsi.org.

Fortunately, now I could there are still `jitsi_*` files in the sub-directories of https://download.jitsi.org/jitsi/ , although not updated anymore.

**Comment by cmeng-git** [comment]
The last release version still on 
https://desktop.jitsi.org/Main/Download

**Comment by testbird** [comment]
Ok, only the debian link has the problem of not pointing to a .deb file.

What do you think, the jitsi issues seem to indicate vulnerabie dependencies that have not been updated for a new build of jitsi.
