### ISSUE TITLE
Discussing the possibility of adding news feed support

### ISSUE THREAD

**Issue by workrockin** [cmeng-git/atalk-android#35]
Hello team,

Great work with the app! I was looking at the readme file and it seems that atalk supports almost all of xmpp protocols and extension. That is a great achievement. I was thinking if it would be possible to add a news feed feature for atalk?

For instance take a look at [movim](https://movim.eu/) that allows the users to post full posts that are publicly accessible.

The news feed feature would require the use of PUB-SUB and PEP protocols both of which are already supported by the app.  This is different from private messaging where the communication is limited to parties talking. If this feature is implemented a talk can be used as a complete social media platform. Where users can post updates. Other people can reply to it or discuss it privately in their chat. 

Thanks!

**Comment by cmeng-git** [comment]
Will take a look

**Comment by workrockin** [comment]
Thank you @cmeng-git . I just discovered something new that I I think might be of use. Prosody an opensource xmpp server has a built in microblogging module called [mod_atom](https://hg.prosody.im/prosody-modules/file/tip/mod_atom/README.markdown) it seems that it uses [XEP 0277](https://xmpp.org/extensions/xep-0277.html) protocol. Thought it might be a good idea to check it out.  

0277 is not currently supported by atalk and it's also marked as deferred by XEP. So not sure what would be the right way to approach this. 

While PUB-SUB can still be used to publish the blogs mod_atom gives back the result in an atom feed format. I'm not sure if you're already using some library that is capable of parsing RSS feeds but there is a good one called [Rome](https://rometools.github.io/rome/).

**Comment by cmeng-git** [comment]
Thank for the info. Currently I am still busy in implementing OMEMO media file sharing and other enhancements for aTalk coming release. This will take a while before I have time to look at your request.

**Comment by workrockin** [comment]
No problem. I'm working on an HTML implementation of the idea myself. Will
keep you updated if I learn anything new.

**Comment by testbird** [comment]
> will take a while before I have time to look at your request

Ah ok, probably also applies to the #1, no?  I was hoping for an upload of https://github.com/cmeng-git/atalk-android/issues/1#issuecomment-487300881 to get f-droid going.

**Comment by cmeng-git** [comment]
aTalk v1.8.5 release has added a web access in the main pager slider; By default,  if you slide the main page slider past conference list, it will access the movim pods. 

You may however define the default  web page access in settings e.g. the company site, where it implements RSS feed or news sharing.

**Comment by workrockin** [comment]
Thanks!

**Comment by cmeng-git** [comment]
aTalk 1.8.8 added support for XEP-0070 and improve webView interface and url click handler etc. Should ease the implementation for organisation RSS feed.

[20190626] XEP-0070: Verifying HTTP Requests via XMPP and WebView Implementation
https://atalk.sytes.net/atalk/faq.html#feature_10

**Comment by workrockin** [comment]
Thank you once more for implementing this feature!
