### ISSUE TITLE
allow chatting and interacting also with email accounts?

### ISSUE THREAD

**Issue by testbird** [cmeng-git/atalk-android#36]
The discussed support for integrating public news feeds / posts / blogs (https://github.com/cmeng-git/atalk-android/issues/35) could really have great potential. (Creating a decentral social network, integrating backwards compatibility to web browsers.... There is no decentral open source frontend (app) that integrates the existing chatting and pub/sub protocols, yet... (like atalk + prosody mod_atom microblogging would).)

A natural completion might be to also make use of a library that would integrate that other online communication protocol, that is actually used by "everybody", i.e. E-Mail, in addition to XMPP:

All the needed SMTP and IMAP messaging and encryption stuff etc. is actually available with the [deltachat-core library](https://github.com/deltachat/deltachat-core).  The most interesting question might be if atalk's architecture allows to easily work with the structure of the high level C API (or its java bindings) provided by deltachat-core, see https://c.delta.chat/ ?

**Comment by cmeng-git** [comment]
Both XMPP chat and Email use completely different protocols, and target for different usage and applications. Integrated them in one app will merely adding another layer on top for user to toggle between the two apps; see no benefit in doing so for aTalk. Request declined.

Note: I have also released XryptoMail in android playstore. XryptoMail is forked from K9.

**Comment by testbird** [comment]
Sure, it is up to what you would like of course.

I dont't think the "Email-chat" standard as implemented by the deltachat-core library would require another app (layer) for the user. It's a "chat over email" standard to exchange short messages, without any need to manually handle `To:` `CC:` and `Subject:` etc.

I think there would practically be no need for a UI change, beyond contacts (address book) having also a field for email in adddition to the xmpp addresses (and manual "prefered" checkbox at most). Incoming email chat messages may simply show up in separate chats, shown in the same chat list. Answering these may trigger deltachat-core to send out an email.

 ...and atalk users can reach the (email) world. :-)

**Comment by testbird** [comment]
Maybe you get a chance to install the "Delta Chat" android app to see how users see the "chat over email" standard (UI wise).

**Comment by cmeng-git** [comment]
aTalk is only an xmpp client that supports simple chat message exchanges. Message chat and email are two different applications that have different usages.
There are already many good email clients that run on android. I ready do not see any benefit to have email interface included in aTalk xmpp client.

Sorry, the request feature is declined.

**Comment by testbird** [comment]
Hi, and thanks again, no problem, it's completely fine if you don't want to employ a  backend library for "chat over email" accounts and connectivity. 

I just had to note that the "chat over email" really works with a simple chat interface, not a classic email interface. If you want you can see and try this for yourself at https://delta.chat .

**Comment by cmeng-git** [comment]
Declined the requested feature support.
