### ISSUE TITLE
make third-party services optional

### ISSUE THREAD

**Issue by testbird** [cmeng-git/atalk-android#37]
Just as having a buld option that only includes open source free software it could make sense for privacy reasons, to have a switch to remove all code connecting to third-party services.

For example, this new:
> Support downloadable Stickers, Bitmoji and Emoji rich content sharing via Google Gboard

(Possible alternative in this example might be to send the sticker with the first message.)

**Comment by cmeng-git** [comment]
Do not quite understand your comment; android studio build variant is in fact a switch to include/exclude third party libraries in an apk generation. This method is recommended by google android team. 

Google Gboard is not part of aTalk,  but an enhancement to Google keyboard; it is similar to keyboard that support different languages input methods. Gboard is just another keyboard enhancement that add rich content for user input.

**Comment by testbird** [comment]
With third-party services I meant atalk making network requests to other addresses than the accounts XMPP server. For example downloading avatars from some avatar tracking company. Not sure how the example above works, though, and whether it allows users to upload and download custom stickers tracked by that companies network.

**Comment by cmeng-git** [comment]
Sorry, I have to decline your requested feature, and this is outside xmpp implementation scope.

The sticker download is not within aTalk control; instead it is the GBoard features that user has control.
