### ISSUE TITLE
XEP-0070 support (2FA over XMPP)?

### ISSUE THREAD

**Issue by poVoq** [cmeng-git/atalk-android#38]
Given that aTalk includes a way to embedd websites it would be pretty cool if it could also allow login via xmpp confirmation. See this website for the details:
https://blog.agayon.be/xmpp_auth_django_demo.html

Thanks for considering.

**Comment by cmeng-git** [comment]
The newly added web access is only a general web interface and has nothing to do with xmpp. It is meant for an organisation to use it to present whatever info the organization want their users to see; this may include company news and RSS feed. All these features are required to be implemented by and on the organization web server. There is no plan to change this.

**Comment by poVoq** [comment]
Yes exactly. But this company website could implement a way for people yo easily log in with xmpp like shown on the demo website I linked.

**Comment by cmeng-git** [comment]
The aTalk web interface will stay as general web site access, so as no to limit its use.
You can get your web server to link with your xmpp server to support user login using xmpp account.

**Comment by poVoq** [comment]
I think you are misunderstanding the function of XEP-0070. I am not asking you to change anything about the general website access, quite the contrary actually.

**Comment by cmeng-git** [comment]
Just learn more info about XEP-0070. I see that this feature is still not widely adapted by the community.
It is not just a client feature, but needs xmpp and web servers to support this.

Do you know any actual implementation of this feature on the following areas:
a. xmpp servers (both ejabberd and prosody do not support this)
b. xmpp clients (cannot find any)
c. web servers (movim?)

Also aTalk hinges heavily on Smack library support, it too does not implement the XEP-0070 protocol.

**Comment by poVoq** [comment]
I don't think the server needs to specifically support it. The first link has a demo site that if I recall correctly worked with my ejabbered server. But yes if smacks does not support it, than it might need to be added there first.

**Comment by cmeng-git** [comment]
Have you verified with a working xmpp client that current ejabberd/prosody  server has no problem handling it. 

Based on the XEP-0070 stanza sent,  I believe that the ejabberd  will throw stanza malformed exception as it does not recognize the \<confirm/> element.

I tends to drop implement any feature that smack does no support it. Unless the feature is widely accepted and of great interest to large group of users. The resource to develop is no trivial, need to convince the return is worth time spent.

**Comment by cmeng-git** [comment]
Status update:
Smack 4.4.0-alpha2: reply IQ cannot contains both StanzaError and ExtensionElement

**Comment by cmeng-git** [comment]
aTalk v1.8.8 release added support for XEP-0070. See online help for more details:

[20190626] XEP-0070: Verifying HTTP Requests via XMPP and WebView Implementation
https://atalk.sytes.net/atalk/faq.html#feature_10
