### ISSUE TITLE
XEP-0184: Message Delivery Receipts

### ISSUE THREAD

**Issue by readyblue** [cmeng-git/atalk-android#40]
Hi,

can you please add message delivery receipts to this amazing client?
It is quite important feature on Android as mobile data can lost signal anytime and it is important to know if message actually arrives or not.

Thanks.
(Thanks for F-Droid version as well)

**Comment by cmeng-git** [comment]
There are other users do not like this feature and disabled it as this somehow intrudes individual privacy.
e.g. Your boss will expect you to reply his/her messages when he/she see that you have read the messages.

aTalk has implemented 
XEP-0198:Stream Management and ReConnection Manager
https://atalk.sytes.net/atalk/faq.html#feature_06

The Stream Management guarantees the reliability that all the messages will get delivered, even under mobile data and network fading, to your recipient when the user is login. 

Implementing XEP-0184: Message Delivery Receipts has not added value in my opinion.

**Comment by cmeng-git** [comment]
aTalk v2.0.3 has Implemented XEP-0184: Message Delivery Receipts with user disable option to made both parties happy

**Comment by readyblue** [comment]
I have just update it from F-Droid and tested it. It works like a charm.

- Option is easy to find if someone want to disable this feature.
- Check sign is clearly visible in the chat window (when enabled).

Many thanks.

**Comment by cmeng-git** [comment]
Many thanks for the feedback and encouragements.
