### ISSUE TITLE
Setting custom notification sound

### ISSUE THREAD

**Issue by readyblue** [cmeng-git/atalk-android#41]
Can you please add option to set custom notification sound?
Preferably for each contact/buddy.
Because default notification sound is too quite (low volume).

Thanks

**Comment by cmeng-git** [comment]
aTalk v2.1.0 release has added support for user defined notification sound.  See online help
[aTalk Notification Events](https://atalk.sytes.net/atalk/faq.html#feature_11)

**Comment by readyblue** [comment]
hi @cmeng-git , I am now able to test v2.1.0 and change "incoming message" notification sound. That works, even play button plays the sound correctly. But unfortunately when I leave the menu and go back to main contact list and new message actually arrives it does not play the sound. Restart does not help either. Then I have change incoming message sound again to default and that sound is played from main contact list. Can you please check?

I have Android 7, so I cannot test that notification features starting Android 8 and later.

**Comment by cmeng-git** [comment]
Yes, I am aware of the problems. They have actually been fixed for the next release in the following areas. I will release it when I have done system test on BOSH connection.

- Ensure all notification events parameters' changes are saved to persistent store (dB)
- Fix non-loop ringtone prematurely stop during playback - always wait for 3 seconds to allow non-loop ringtone to play at
- Fix AndroidCallListener#fireMissedCallNotification() with incorrect eventType, must use NotificationManager.MISSED_CALL

**Comment by cmeng-git** [comment]
Has released aTalk version 2.1.1 with the fixes. Please check and verify it does resolve your problem.

**Comment by readyblue** [comment]
Yes, I have test it now and it works. I was able to set custom notification sound.
Thank you very much for implementing this feature. It is again very well done. Specially love the sample "play button" to play the current notification sound (as a test).

**Comment by cmeng-git** [comment]
Thanks for the feedback
