### ISSUE TITLE
Documentation for setting up the servers

### ISSUE THREAD

**Issue by waqar-ahmed** [cmeng-git/atalk-android#44]
Hi,
Thank you for making this app. I would like to ask, is there any documentation how to setup the server for XMPP and VOIP and connect them together using jingle (if jingle is being used). Moreover, the documentation for modules what is it doing. If there is any, it would be great to have that available as well.

Thank you.

**Comment by cmeng-git** [comment]
Hi,
aTalk is only a client. For server setup, you should put your question on the online forum, so more experts can give you advice.

As for the aTalk, it has already implemented client side VOIP support,  but server must configure to support this: You may refer to the following for more info:
https://github.com/cmeng-git/atalk-android/issues/10
https://atalk.sytes.net/atalk/faq.html#media_04

For aTalk testing, I am using ejabberd; there is an online help on the setup.
https://docs.ejabberd.im/admin/guide/

There are other open source xmpp servers, please do an online search yourself.
