### ISSUE TITLE
Autoretry after "undecided omemo identity" verification

### ISSUE THREAD

**Issue by licaon-kter** [cmeng-git/atalk-android#52]
Steps:
1. write
2. pop-up with verification, verify 2 out of 3
3. message not sent
4. write again
5. pop-up with verification, verify last one
6. message not sent
7. write again
8. message sent

Expected:
1. write
2. pop-up with verification, verify 2 out of 3
3. pop-up with verification, verify last one
4. message sent

**Comment by cmeng-git** [comment]
Actually I have already attempted before, spend days try to implement what you are requesting. But failed to find a clean solution for the problem.

I will take a look again when have more time.

**Comment by cmeng-git** [comment]
I just recall there is actually an undesired case, if the user refuses to authenticate any of the undecided buddies for some reason; then aTalk will be locked into the endless loop, user is unable to exit the chat session.

This is one of the main reasons aTalk decided not to perform the auto retry on behalf of the user. Instead it implements to allow user just click the last send message, aTalk will reinsert the last message into the entry Box for user resend.

**Comment by cmeng-git** [comment]
Finally manage to implement as requested for aTalk v2.0.6 release.
