### ISSUE TITLE
Don't add account unless logged in

### ISSUE THREAD

**Issue by licaon-kter** [cmeng-git/atalk-android#56]
Steps:
1. Write "user" and _password_
2. Press add
3. Account added in background
4. Account is active
5. Account is always offline _(Can't login since no domain was specified)_
5. Write "usernamewithatipo@domain.tld" and _password_
6. Account added in background
7. Account is active
8. Account always offline _(Can't login, bad username)_
9. Write "correctuser@domain.tld" and _wrongpassword_
10. Account added in background
11. Account is active
12. Account always offline _(Can't login, bad password)_

Expected behaviour:
1. Try to login
2. Fail
3. Stay in the same view
4. Ask the user to correct the input data until you can actually login

Actual results:
1. Look at accounts screen see 3-4-6 useless accounts
2. Feel ashamed of your dumbness
3. Try to deactivate them, fail
4. Start deleting them one by one

**Comment by cmeng-git** [comment]
Yes, I am fully aware of the problem. However the way account being setup is inherited from Jitsi source. Fixing this required some major changes to the architecture, and will certainly create many more problems than you have described. This the main reason why I was not taking the risk to make this correction, at least for now.

**Comment by licaon-kter** [comment]
Maybe when the UX gets some Material love? ;)

**Comment by cmeng-git** [comment]
The upcoming aTalk v2.0.6 release has improved the account UI settings.
The Account ID (user name) is now user editable; in both the account re-login menu and Account Settings....
