### ISSUE TITLE
Audio and video noise problems.

### ISSUE THREAD

**Issue by zbh924** [cmeng-git/atalk-android#57]
Hello, we just tested the audio and video call and found that there is a big noise problem.

**Comment by cmeng-git** [comment]
Can you please send me the debug log.

Please help to provide the following info:
1. Are you doing just a plan or call with ZRTP encryption?

2. Please call while both devices are connected via WiFi? Are they having the same problem?

3.Are both devices running aTalk and what are the video/audio codec setting?

4. Do you have the noise problem when making audio call only?

5. Please do a local video/audio recording and playback. Do you see any noise problem.

**Comment by zbh924** [comment]
Hello, we are now choosing the client. Has not yet entered development. Just took the two mobile phones WiFi and tried the audio and video functions. We will enter development soon. Is your audio and video function developed on the basis of a third-party charging tool? Still using free webrtc development?

**Comment by cmeng-git** [comment]
Forget to mention that you must ensure the two test devices are placed far apart to avoid any audio feedback from each other.

aTalk does not use webRTC.

**Comment by cmeng-git** [comment]
Look like it is not a genius problem.
