### ISSUE TITLE
Make more commits / better git log

### ISSUE THREAD

**Issue by Perflyst** [cmeng-git/atalk-android#60]
Currently aTalk has commits like Telegram, one mega commit which contains the new version.
That is not quite nice to follow and ugly from the point of view of open source.

I also think it might be more difficult for new contributors. Would you mind pushing each new feature / bugfix as own commit like nearly everyone else does? Would really appreciate it.

**Comment by cmeng-git** [comment]
Sorry,  I would still prefer to do commit on every new release.
