### ISSUE TITLE
java version

### ISSUE THREAD

**Issue by shicheng-freedom** [cmeng-git/atalk-android#62]
What is the java version required for this software?

**Comment by cmeng-git** [comment]
It is specified in the build.gradle file
    compileOptions {
        sourceCompatibility = '1.8'
        targetCompatibility = '1.8'
    }

Not sure this is what you are looking for.

**Comment by shicheng-freedom** [comment]
Does this mean it is based on Java 1.8?

**Comment by cmeng-git** [comment]
It means the aTalk source is compatible for java 1.8 compilation.

Any reason why you need to know the java version?
Actually I do not quite understand what you actually need.

**Comment by shicheng-freedom** [comment]
I want to use atalk to make an app, which may be commercial. I know that the free jdk version that can be commercialized is up to jdk 11.0.2. I would like to ask you about the commercial and free jdk version that is supported by atalk.
I look forward to your answer and wish you good luck.

**Comment by cmeng-git** [comment]
Please note that  aTalk is under 

http://www.apache.org/licenses/LICENSE-2.0

Any derivative of aTalk is also under the same license control and it too has to be open source.

**Comment by shicheng-freedom** [comment]
This is not a problem. What is the minimum adaptation of the atalk Android version?

**Comment by cmeng-git** [comment]
Kindly refer to the build.gradle file, many of the infos are specified in there.

**Comment by shicheng-freedom** [comment]
Ok, thank you for your answer.
