### ISSUE TITLE
Support for jingle file transfer is missing

### ISSUE THREAD

**Issue by Ri0n** [cmeng-git/atalk-android#64]
Just tried to send a file to Psi, but it atalk used legacy SI protocol instead of Jingle

**Comment by cmeng-git** [comment]
Jingle file transfer is not supported on aTalk. Please see on the online help on the file transfer protocol supported by aTalk.

**Comment by Ri0n** [comment]
I've implemented SIMS over Jingle-FT in Psi.  And also Psi supports Jingle calls that's why I installed aTalk - to test the calls. and SIMS would be a nice bonus if it ever supported by aTalk.
Legacy is supported there too but SI file transfer is deprecated by standard.

So lets consider this issue a feature request.

**Comment by cmeng-git** [comment]
aTalk v2.9.2 has added support for Jingle File transfer for both plain, and omemo encrypted file via JET.
