### ISSUE TITLE
Don't access camera on start

### ISSUE THREAD

**Issue by licaon-kter** [cmeng-git/atalk-android#65]
...as this makes my Xiaomi 9T Pro front camera pop-up.

2.1.1 F-Droid, MIUI11 Android 10, all permissions granted

**Comment by cmeng-git** [comment]
With the current aTalk architecture design, it needs to check the present of cameras and to find out the camera capabilities. These info are required for aTalk initial call parameters/options setup.

In android OS design, the camera capabilities can only be checked with the camera in active mode. aTalk will turn off the camera immediately after the check. This should only happen once on first launch of aTalk. Even with the checking for the camera is delayed till later time, your observed problem will still exist.

Changing aTalk process flow on how the camera is checked is a major change to its architecture, and not advisable.

**Comment by licaon-kter** [comment]
Why don't you cache this info? It's not like my cameras will ever change...

**Comment by cmeng-git** [comment]
I need to think about this.
If I am not wrong, there are android devices that allow use of external cameras.

By the way is there a reason why you exit aTalk every time. Conversation does not have an EXIT button. May be aTalk should consider this as an option.

**Comment by licaon-kter** [comment]
LOL did you just blame me? Nice one

The app can't cope with 1 chat and 2 MUCs ejabberd/Conversations, so it restarts several times, each time it seems to either ask for battery optimizations enabled and surely every time it pop-ups the camera

**Comment by licaon-kter** [comment]
> If I am not wrong, there are android devices that allow use of external cameras.

Mostly failed products yes.

**Comment by cmeng-git** [comment]
No. It is not my intention to blame any party to resolve problem. I would like to understand the behaviour of each user so I can make aTalk better.

Until today, it is always in my mind whether there is a need to offer user the Exit option. I would like to know how users use the option.

Sorry if my last comment sound that way.

**Comment by cmeng-git** [comment]
Camera setup parameters are now saved in persistent storage. Fixed in aTalk version 2.1.2

**Comment by licaon-kter** [comment]
Thanks
