### ISSUE TITLE
Audio and video function

### ISSUE THREAD

**Issue by shicheng-freedom** [cmeng-git/atalk-android#68]
Hello, why don't you choose WebRTC for audio and video? Because many big companies will choose WebRTC. What kind of considerations do you consider based on the lack of WebRTC? I look forward to your answer, thank you very much!

**Comment by shicheng-freedom** [comment]
Supplement: For example, the product used by WeChat is WebRtc.

**Comment by cmeng-git** [comment]
WebRTC is meant for web access and is not compatible with XMPP protocol where aTalk is based on.

**Comment by shicheng-freedom** [comment]
Ok, thank you very much for your reply, which is very helpful to me.
