### ISSUE TITLE
Composing messages with special characters and new lines

### ISSUE THREAD

**Issue by Aq32** [cmeng-git/atalk-android#70]
It seems that when you type in chat the "<" (angled bracket/less than) symbol it is eaten up and text that follow it can be too. Are there special characters that aren't allowed or some other text formatting that aren't documented in the FAQ? Is there some escape character(s) needed to enter special characters like the "<" symbol? Considering the ">" symbol seems to work this might be a bug. I haven't tested extensively for other characters.

Also Is there a way to add a new line/line break in the same message block? It would be better for composing a message rather than breaking a message into separate chunks just because the time changes by one minute for example. 
I think the edit feature also only permits editing of the most recent message too which might be part of the program design. Could this be changed to include more than just the most recent message?

**Comment by cmeng-git** [comment]
aTalk message sending supports [XEP-0071: XHTML-IM](https://xmpp.org/extensions/xep-0071.html) protocol. Therefore if you want to send any message contains html tag character, you must escape the character e.g. sending \&lt;result> will be received as \<result>.

[XEP-0308: Last Message Correction](https://xmpp.org/extensions/xep-0308.html) only allows the correction made to the last sent message. aTalk implementation follows this standard.

Actually aTalk allows sending of messages with line breaks. It is during message display, the line break is accidentally get stripped off, while trying to take care android problem in showing all links as clickable. Will fix this for next release.

Note: The received message with line break is displayed properly on other non-aTalk clients.

**Comment by Aq32** [comment]
Ah thanks for the clarification.

**Comment by cmeng-git** [comment]
Solutions implemented in aTalk v2.1.3, you should be able to input '<' and new line break.
aTalk v2.1.3 now also support send and receive of instant messages that contain lightweight text markup (XEP-0071: XHTML-IM)
e.g &lt;em>Wow&lt;/em>, I&apos;m &lt;span style='color:green'>green&lt;/span>

Please verify.

**Comment by Aq32** [comment]
Confirmed. XHTML-IM works, can type < symbol on it's own now and and new lines also display intuitively.

Not sure if it's a big problem but if you leave your tag opened then your next message can carry over the tag (eg. <blockquote>... until closed with </blockquote>)

**Comment by cmeng-git** [comment]
aTalk implements xep-0071, and hence its specified rules must be followed when entering tags:
Please see the following.

[XEP-0071: XHTML-IM](https://xmpp.org/extensions/xep-0071.html
8. Business Rules
XHTML-IM is a reduced set of XHTML 1.0 and thus also of XML 1.0. Therefore all opening tags MUST be completed by inclusion of an appropriate closing tag.

[XHTML Rules and Syntax](http://www.ssi-developer.net/xhtml/xhtml-syntax.shtml)
