### ISSUE TITLE
Long lines in chat messages obscured by the side Send button

### ISSUE THREAD

**Issue by Aq32** [cmeng-git/atalk-android#71]
As the title say. Long message line(s) gets obscured by the send button overrunning past the white textbox. This also occurs both in portrait or landscape mode across a single or multiple lines.

![aTalkPortraitTextOverrun](https://user-images.githubusercontent.com/162827/68781758-278d7400-0630-11ea-9b4c-9c51d79981f9.png)
![aTalkLandscapeTextOverrun](https://user-images.githubusercontent.com/162827/68781759-278d7400-0630-11ea-839a-fb46a6d940e6.png)

**Comment by cmeng-git** [comment]
Thanks for the feedback. I have fixed the problem and will be in next aTalk release.

**Comment by cmeng-git** [comment]
Fix implemented in aTalk v2.1.3, please verify.

**Comment by Aq32** [comment]
Can confirm that the overflow text boundary is now fixed in 2.1.3 Thanks!
