### ISSUE TITLE
[Feature request] Share files from outside of aTalk directly

### ISSUE THREAD

**Issue by Aq32** [cmeng-git/atalk-android#72]
Currently aTalk allows adding of attachments (Pictures, Videos, Files) from within itself but is it possible to allow sending of files etc by Android's "Share" feature? Some apps allow sending files into other apps where the app itself will handle sending the file. Some apps even allow Share files to specific contacts within the Share interface to more efficiently send files.

**Comment by licaon-kter** [comment]
Intents...yes.

**Comment by cmeng-git** [comment]
The released aTalk v2.1.4 has implemented the share from outside function.
It also added support for share with, quote and forward. Please verify.

**Comment by licaon-kter** [comment]
Great, but please name your intent as "aTalk" and not "Share..."

**Comment by cmeng-git** [comment]
It is actually a share interface, and user needs to end the ui after sharing to return to main menu. Making it the same name as aTalk may confuse user as the main contact list.

**Comment by licaon-kter** [comment]
When I share to, I get a list of apps...all the apps are named with their proper names...yours is has the right icon but its name is "Share..."

At least on Android 10 that is.

**Comment by cmeng-git** [comment]
Thank for pointing it out. I did not realise the activity name is reflected in the chooser. Will fix it in next release.

**Comment by cmeng-git** [comment]
updated in v2.1.5
