### ISSUE TITLE
add feature

### ISSUE THREAD

**Issue by ShiChengPersonal** [cmeng-git/atalk-android#76]
Hello, our company's projects have dozens of function points, such as one of them is to change the background image and font size color, in a single chat or group chat page. Whenever your code version is updated, we need to copy and paste these dozens of function points again. We noticed that your version update is updated every two months, so our workload will be very large. Is there any There is no good way to do this, similar to the Openfire plugin, or other ways that make it easier for us to develop. Thank you very much.

**Comment by subpub** [comment]
Maybe you can send those changes upstream through pull requests so your changes get merged here and you don't have to keep changing stuff?  :wink:

**Comment by cmeng-git** [comment]
Please limit your request to aTalk app only.

**Comment by ShiChengPersonal** [comment]
Ok, thank you.
