### ISSUE TITLE
Registration question

### ISSUE THREAD

**Issue by ShiChengPersonal** [cmeng-git/atalk-android#77]
Hello, I found some problems when I conducted the aTalk test. I don't know if my test method is wrong or aTalk has some problems. I want to discuss these issues with you and hope to give me some suggestions.
Test environment: computer system: ubuntu1804; local server: Openfire4.4.3; simulator: Geniemotion based on Android 5.0 machine A, Android 9.0 debugging machine B.
Test situation: When I use A to register the account 123456, I can use it normally. At this time, I registered the account 123456 again on B, and it was successful. The online status is displayed on both devices, but the account 123456 cannot send messages to each other, and only one user with the account number 123456 is displayed on the server. However, A and B can simultaneously use the account 123456 to successfully send a message to other accounts 456789. At this time, the message received by 456789 is displayed by one user, but both messages are received.
When this happens, there is a problem in switching between different account logins in one device. The friend's chat list will have its own account. For example, the switch account is 456789 in device B. At this time, the account's friends have two accounts. For the chat record of 123456, the chat record with the account number 456789 appeared, and the icon of voice and video appeared at this time.

**Comment by cmeng-git** [comment]
Will do my best to answer your questions, although I may not have fully understand your questions.

Prerequisite for correct operations:
#1. For user to have multiple sessions login, both user account must use different resources e.g.
 mA = 123456/user1  and mB = 123456/user2.
#2. Both the client and server must support message carbon i.e. XEP-0280: Message Carbons. aTalk support xep-0280.

> The online status is displayed on both devices, but the account 123456 cannot send messages to each other,

If condition 2 is met. sending message from either user1 or user2 will always carbon copy to each other i.e. all sent messages will appear on both user chat windows.

>  and only one user with the account number 123456 is displayed on the server

This is correct behaviour. Server will only display one user name on its record. and both of the same user but with different resources.  

> A and B can simultaneously use the account 123456 to successfully send a message to other accounts 456789. 

This is always true, as the forward of all sent messages  are carried out by the server.

> At this time, the message received by 456789 is displayed by one user, but both messages are received.

I suppose you meant  .. but both messages sent from user1 or user2 are properly received. This is correct operation.

> When this happens, there is a problem in switching between different account logins in one device. The friend's chat list will have its own account. For example, the switch account is 456789 in device B. At this time, the account's friends have two accounts. For the chat record of 123456, the chat record with the account number 456789 appeared, and the icon of voice and video appeared at this time.

Do not understand what you meant. However if both #1 and #2 conditions are met. You should not encountered any problems in the operations as you described when using aTalk.
You should be able to make video call to user(456789) from either user1 or user2. OR from user(456789) to user1/user2; server will pick the one (user1/user2) with the higher priority setting or user with more recent session if both have the same priority setting.
