### ISSUE TITLE
Sending a link becomes sending a file.

### ISSUE THREAD

**Issue by Folaht** [cmeng-git/atalk-android#78]
- Version: 2.1.2
- Phone
  - 1. Samsung A20s
  - 2. Xperia XA20 Plus
- OS
  - 1. Android 9
  - 2. Sailfish 3

To any receiver, any link send turns into a file send.

**Comment by cmeng-git** [comment]
If you want to send a link, you need to precede it with one or more non-space characters. In order to provide harmonised UI to handle file transfer, aTalk treats link as http file downlaidd link if it contains only a link without preceding characters.

**Comment by Folaht** [comment]
This is new to me. 
Thank you for the explanation.

**Comment by cmeng-git** [comment]
Yes, this is current behavior for aTalk. Previously I always used this feature to test aTalk http file upload services. I will take a look if this restriction can be remove in next release.

**Comment by Folaht** [comment]
I just found out that sending regular links like [https://qwant.com](https://qwant.com) [https://google.com](https://google.com) as a link alone crashes aTalk.
....
Oh oh, I tested this seconds before on my girlfriend!

**Comment by cmeng-git** [comment]
Please update to aTalk v2.1.3 that should have fixed the problem.

**Comment by cmeng-git** [comment]
aTalk v2.1.4 has extended check and hopefully should minimize the observed problem.
