### ISSUE TITLE
Random room opened when exiting Account settings

### ISSUE THREAD

**Issue by licaon-kter** [cmeng-git/atalk-android#80]
2.1.3 F-Droid

Normal view, go to menu, Account Settings, choose account, don't change anything, don't use the titlebar arrow BUT use the device backarrow (or back gesture in my case)

One (of my two rooms) randomly opens, the titlebar room title is correct, the subtitle (room subject) might be either the correct one or the one from the other room(!!), the room won't disappear all by itself, I need to hit back.

On back I'm now taken to the accounts screen.

Why does the Account setup screen behave differently on titlebar arrow (nothing happens) versus device back (popup appears with Commiting Storing account changes, please wait) ?

**Comment by cmeng-git** [comment]
> choose account
What exactly you mean by choose account?
Click ON/OFF or enter into the detailed account setting

If you click on the ON/OFF button, aTalk will take immediate action to register or unregister the account from the server pending on the new state of the button.
If you made changes to the account settings, then aTalk will logout and login again when you return to the account list screen. This is to ensure the new settings are in effect.

By right there should be no different between the TitleBar Back or BackKey, aTalk does not take any special action on these two buttons. OS should just goes back to the previous screen.

Opening of the rooms should only happen if you have set rooms as auto-joined. Opening of auto joined room will happen once the account has registered with the server. 

Do any of your rooms set to auto-joined?
If the room randomly open without the auto-joined option being enabled. Please send me the debug log when this happened, so I can take a look. also to understand what causes the incorrect display of the room subject.

**Comment by licaon-kter** [comment]
> What exactly you mean by choose account?

Enter into the detailed account setting

> If you click on the ON/OFF button

I did not

> If you made changes to the account settings

I did not

> Opening of the rooms should only happen if you have set rooms as auto-joined.
Do any of your rooms set to auto-joined?

Note that no room is opened (well except this glitch of course: https://github.com/cmeng-git/atalk-android/issues/75#issuecomment-561504537 ) when I open the app. Maybe they are, if so wouldn't aTalk open them on start? It does not, why would it opened it now between EDIT ACCOUNT view and ACCOUNT list view though?

> Opening of auto joined room will happen once the account has registered with the server.

The app is started for a while already, no rooms opened, no chats opened.

**Comment by cmeng-git** [comment]
> Note that no room is opened (well except this glitch of course: #75 (comment) ) when I open the app. Maybe they are, if so wouldn't aTalk open them on start? It does not, why would it opened it now between EDIT ACCOUNT view and ACCOUNT list view though?

All auto-joined rooms should be opened automatically when aTalk has detected that the user account has "REGISTERED" i.e. login with the server. This should not depend whether you just start up aTalk or changing account setting. An opened rooms will have their room names display as BOLD in the room list view.

If the auto-joined room does not open on start, I need the debug log to understand the problem.

> Right, tested by modifying something and a random room opens on back, but (unlike the other issue) it does not close, stays open, hitting back again takes me to Accounts view, and another back again to the contacts view.

aTalk does not auto close an auto-joined room that has been opened. It is just like user has clicked on the room item. User needs to manually close the room. Hitting back is taken care by android OS; when user press the BackKey, OS just pop the stack and return to the last activity as retrieved from the stack. This is android OS normal behavior.

**Comment by licaon-kter** [comment]
Ok, I've got it on video.

I could send it to you via xmpp, but now it can't use OMEMO in your chat, do ping me when you are online.

Steps to repro:
* clean app data
* give all perms
* add account
* go to account settings
* go to connection settings
* toggle "Google Cntacts search" to OFF _(what is this anyway? some Talk/Hangouts leftover?)_
* use back gesture (not titlebar arrow!)
* see the bug (account is disconnecting, reconnecting, MUC pops out)
* go to account settings again
* DO NOT DO ANYTHING, don't modify anything
* use back gesture (not titlebar arrow!)
* see the bug (account is disconnecting, reconnecting, MUC pops out)

But, after exiting the app and reopening this is not triggered any more, so I guess the "settings where NOT modified" flag or something is not saved unless one exits the app.

**Comment by cmeng-git** [comment]
Please send the debug log to my gmail account
cmeng.gm@gmail.com

**Comment by licaon-kter** [comment]
Umm, lolwut? If I get the time to get it and clean it up I'll send it to your xmpp account.

**Comment by cmeng-git** [comment]
Issue is a repeat or problem occur under the same mechanism of  
MUCs open on start but you can't access them #75

Close and continue discussion on #75
