### ISSUE TITLE
Titlebar subtitle is subject of random room

### ISSUE THREAD

**Issue by licaon-kter** [cmeng-git/atalk-android#81]
2.1.3 F-Droid

During testing for https://github.com/cmeng-git/atalk-android/issues/80 I saw this rather often.

For MUCs
![1](https://user-images.githubusercontent.com/2282799/70136592-3a6df400-1684-11ea-867d-b8787a3c345b.jpg)
![2](https://user-images.githubusercontent.com/2282799/70136594-3b068a80-1684-11ea-866c-ff7791643dbc.jpg)

And even for my own account
![3](https://user-images.githubusercontent.com/2282799/70136595-3b068a80-1684-11ea-89df-1988a575d889.jpg)

**Comment by cmeng-git** [comment]
Does this happen only when you are doing page slide to difference conferences room OR
The subtitle just randomly changes by itself while you are in the same conference chat session?

Will the text content returns to the actual room subject eventually if left untouch?

The subTitle area is meant to display the conference room Subject. The text content will get updated whenever it receives a new room subject change by any of the room members.

Will it be possible, one of the members is sending some notifications by changing the room subject?

I see the text "Join the Converation. FAQ: ...", any idea where this text come from?

**Comment by licaon-kter** [comment]
No intentional room access (but as seen in #75 one might pop-up on start) for the user picture.

No intentional room access (but #80 will open one) for the MUC picture.

For the user picture, opening a chat or settings will fix it, for the MUC ones....I dunno, I usually hit back and it goes to the other view (again I never opened any MUC intentionally yet).

 Not sure how it works, I guess I receive the subject on connect, but does that mean someone sets it?

 "Join the Conversations..' is the Conversations support MUC subject/title, while the "ejabberd.im" one is from the other room.

I'll see about the log.

**Comment by cmeng-git** [comment]
> Not sure how it works, I guess I receive the subject on connect, but does that mean someone sets it?
> "Join the Conversations..' is the Conversations support MUC subject/title, while the "ejabberd.im" one is from the other room.

Please See [XEP-0045: Multi-User Chat](https://xmpp.org/extensions/xep-0045.html#enter-subject)
7.2.15 Room Subject
After the room has optionally sent the discussion history to the new occupant, it SHALL send the current room subject. This is a <message/> stanza from the room JID (or from the occupant JID of the entity that set the subject), with a <subject/> element but no <body/> element, as shown in the following example.

Yes, the subject is entered by the room creator/owner or any member whom has the access right. The server will send the subject stanza again when any of the room participants changes the subject.
So it seems the previous few screenshots that you have attached have correctly display the room subject.

The room will only auto open the group chat session on start when the autojoin option is enabled. Can you please check the bookmark of each room to ensure "Auto Join" option remains unticked.

**Comment by licaon-kter** [comment]
You keep saying auto-join...while I repeat that I see no open MUCs...except that MUCs pop-up at random that disappear after 1 second or appear when exiting Account settings (those 2 other issues).

If atalk sees MUCs with the auto-join flag, why not open them normally then? 

FYI, I only see what the 3rd picture in the first post shows, a Contacts section and one contact.

**Comment by cmeng-git** [comment]
Look like I really need the debug log to get to the root of the problem.

**Comment by cmeng-git** [comment]
The actionBar sub-title is actual the displaying the room subject as per design. Issue closed.

**Comment by licaon-kter** [comment]
Third picture... no room opened... same behaviour on 2.1.4, maybe #75 fixes them.

**Comment by cmeng-git** [comment]
Sorry, not fully understand your comment:

Are you saying the problem has been fixed or still happening in v2.1.4.
If so, appreciate if you can send me the debug log for better understanding of the problem and finding a fix for it.

**Comment by licaon-kter** [comment]
Still an issue on 2.1.4, with auto-join rooms. I'll to get a log eventually.
