### ISSUE TITLE
Read source

### ISSUE THREAD

**Issue by ShiChengPersonal** [cmeng-git/atalk-android#83]
Hello, I have some doubts when reading your source code. I want to know what aTalk does when it receives friend data. For example, how is the buddy list on the main page implemented, and how is the buddy data read, because I want to implement the buddy list address book. Looking forward to your answer, thank you very much.

**Comment by cmeng-git** [comment]
Sorry i do not have the resource nor the time to answer your question.

**Comment by ShiChengPersonal** [comment]
OK, thank you very much for your reply.
