### ISSUE TITLE
Unencrypted photos don't show a preview when received by Conversations

### ISSUE THREAD

**Issue by licaon-kter** [cmeng-git/atalk-android#84]
...in other apps like Conversations or Converse, they end up as plain links.

But once I send them with OMEMO they always get a preview

(so MIME issue? but links have extension)

2.1.4 selfbuild

**Comment by cmeng-git** [comment]
When a file is sent with OMEMO encryption, the actual file link starts with aesgcm://.....
This is not a normal http file link where user can click and download from the server. The application must process this link to download and decrypt the file content.

The received file link must have the proper file extension. aTalk uses the original file name as received. If the send file is without a proper ext, aTalk may not be able to know it is a media file and show a preview of it. android OS uses the file ext to properly decode the mime type.

In the latest android OS, when a file is shared via a content provider, android only provides a file ID (containing digits only) without any extension. aTalk v2.1.4 has taken some steps to re-insert the ext if possible, before sending the file. aTalk should be able to show the preview if the correct file ext is reinserted.

However if the file to be sent, where aTalk has direct access, then aTalk does not take any action to modify the original file nor add an extension to it. So it the original file does not have an ext, then aTalk may have problem to show the preview.

I need to know which of the above problem you are actually referring to.

**Comment by licaon-kter** [comment]
Link appears as: `https://upload.mydomain.tld/hash/hash/filename.extension` in other clients

In aTalk appears as thumbnail, `filename.extension` (size)

**Comment by cmeng-git** [comment]
> Link appears as: `https://upload.mydomain.tld/hash/hash/filename.extension` in other clients
> In aTalk appears as thumbnail, `filename.extension` (size)

aTalk decides to make all the file transfers including the HttpFileUpload to have the same UI as all others file transfer protocol; hiding the details and only to display the filename instead of a full link. The links may have aesgcm:// that is not clickable by user to start the download.

If you want to know the full link, you can select the view, copy and paste to the text entry box, it will display the full link info.

I forget to mention that prior to v2.1.4, aTalk uses the content provider filename as it. So you pick any of these files (without the ext) for attachment, other receiver clients may not be able to display the preview.

> /LE: Same way of sending the file, but with OMEMO enabled, and now preview appears. Hence me thinking that maybe there's a difference on how the file metadata is sent when unencrypted.

Are you referring to aTalk or other clients? Actually there is no extra metadata accompanied with the link except the encrypted key info when you sent file in OMEMO chat.

In aTalk for a received file without ext, it will attempt to decipher the file byte contents to determine if it a media file, hence to show preview if possible.

**Comment by licaon-kter** [comment]
2.1.5 F-Droid, same issue

In atalk it looks the same, same name, same preview, in Conversations unencrypted has a link, encrypted has a preview.

The Help->Report bugs log is useless

```
2020-01-04 11:54:40.656 INFO: [1212] fmj.loadDocument() FMJ registry document version 0.1
2020-01-04 11:54:40.658 INFO: [1212] fmj.loadFromFile() Loaded registry from file: /data/user/0/org.atalk.android/files/.fmj.registry.xml
2020-01-04 11:54:40.673 INFO: [1212] fmj.commit() Wrote registry file: /data/user/0/org.atalk.android/files/.fmj.registry.xml
2020-01-04 11:54:40.674 FINE: [1212] fmj.getPluginInfo() Problem loading plugin com.ibm.media.parser.video.MpegParser: java.lang.ClassNotFoundException: com.ibm.media.parser.video.MpegParser
...more of this plugin nonsense

2020-01-04 11:54:42.322 INFO: [1235] org.jivesoftware.smackx.avatar.vcardavatar.VCardAvatarManager.downloadVCard() Downloaded vcard info for: user@domain.tld; Hash = hash
2020-01-04 11:54:42.325 INFO: [1224] org.jivesoftware.smackx.avatar.vcardavatar.packet.VCardTempXUpdate.setAvatarHash() Account avatar hash updated with (old => new): 
null
hash
```

Also both logs are rather identical un/encrypted.

Did I miss some "enable debugging" toggle in settings?

**Comment by cmeng-git** [comment]
aTalk implementation in HTTP file transfer UI's are completely different from Conversations. Appreciate if you only report the problem you see in aTalk; do no complicate the whole issue with Conversations implementation.

aTalk does not show the actual download link, but only the filename of the transferred file.
May I know what are the actual filenames being displayed in aTalk download view holder, that are having problem with the previews after the files are downloaded.
Also are all these files being sent from another device with aTalk client?

If you really want to know the actual link for download, you can select (long press) the download view holder, copy then paste into the entry box. This link is what Conversation is showing.

**Comment by licaon-kter** [comment]
> Appreciate if you only report the problem you see in aTalk; do no complicate the whole issue with Conversations implementation.

So I should close this and not report issues when atalk interacts with other clients? Maybe I'm lost in translation...

> May I know what are the actual filenames being displayed in aTalk download view holder

`nameofpicture.jpg`

> that are having problem with the previews after the files are downloaded.

In Conversations only a link appears, a text, there's nothing to download (from Conversations point of view at least).

> Also are all these files being sent from another device with aTalk client?

Are we lost in translation again? aTalk sends the files... other clients (that are NOT atalk) receive either a file to show a preview or a text (link).

**Comment by licaon-kter** [comment]
![asatalkseesit](https://user-images.githubusercontent.com/2282799/71783969-fbfe8880-2fe5-11ea-962a-11039936de85.jpg)
vs
![asConvseesit](https://user-images.githubusercontent.com/2282799/71783971-002aa600-2fe6-11ea-842e-ec89c2813942.jpg)


FYI, the links are the same, `aesgcm://` for encrypted and `https://` for unencrypted.

**Comment by cmeng-git** [comment]
I am a bit confuse what is the exact problem are your referring to:
#1. Unencrypted photos don't show a preview or 
#2 Random crash 2.1.5 #86
I am presumably you are referring to #1.

What I understand from you last comment and attached images, you are showing me the different in the file transfer mechanisms and UI implementation between aTalk and Conversations. As I have mentioned, aTalk file sharing implementation is different from Conversations.

Conversations supports only jingle file transfer and HTTP file upload protocols, but not the legacy file transfer protocol. Whereas aTalk implement only HTTP file upload and legacy file transfer protocols.
Therefore in order for aTalk to send file to Conversations, it can only use HTTP file transfer protocol.
This is the reason why only HTTP links are sent to Conversations for both the unencrypted (plain) and encrypted (OMEMO) file sharing. Conversations implementation decides to only download the encrypted file from server and display a preview of its content, but show the link instead if it is a https// link. Conversations team can only answer why there is an implementation differences between https// and aegcm:// links.

When you send unencrypted file between two Conversations clients, they use jingle file transfer protocol to send file. Therefore conversation is able to show a preview of the received unencrypted file content.
 
If you send file file between two aTalk clients, you too will see the same as Conversations.

**Comment by licaon-kter** [comment]
Maybe I got HTTP upload wrong, but all the files in that picture from Conversations have an actual aesgcm or https link on longpress, so I'd guess that Jingle was **not** used.

Afaik, Jingle is used in Conversations only if HTTP upload is not available or if file size is bigger that the server max file size for HTTP upload.

**Comment by cmeng-git** [comment]
Issue closed as observation/answer lies with conversations implementation.
