### ISSUE TITLE
Random crash 2.1.5

### ISSUE THREAD

**Issue by licaon-kter** [cmeng-git/atalk-android#86]
F-Droid

Opened atalk, contact, pressed encryption icon (didn't change anything), pressed attach icon...atalk restarted

```
01-04 13:01:14.699 24332 24332 D AndroidRuntime: Shutting down VM
01-04 13:01:14.700 24332 24332 E AndroidRuntime: FATAL EXCEPTION: main
01-04 13:01:14.700 24332 24332 E AndroidRuntime: Process: org.atalk.android, PID: 24332
01-04 13:01:14.700 24332 24332 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.ExpandableListConnector$PositionMetadata android.widget.ExpandableListConnector.getFlattenedPos(android.widget.ExpandableListPosition)' on a null object reference
01-04 13:01:14.700 24332 24332 E AndroidRuntime: 	at android.widget.ExpandableListView.expandGroup(Unknown Source:8)
01-04 13:01:14.700 24332 24332 E AndroidRuntime: 	at android.widget.ExpandableListView.expandGroup(Unknown Source:1)
01-04 13:01:14.700 24332 24332 E AndroidRuntime: 	at org.atalk.android.gui.chatroomslist.model.BaseChatRoomListAdapter.lambda$expandAllGroups$0$BaseChatRoomListAdapter(BaseChatRoomListAdapter.java:137)
01-04 13:01:14.700 24332 24332 E AndroidRuntime: 	at org.atalk.android.gui.chatroomslist.model.-$$Lambda$BaseChatRoomListAdapter$O8cvgA1F4llDu50clTZsgpKwCSM.run(Unknown Source:2)
01-04 13:01:14.700 24332 24332 E AndroidRuntime: 	at android.os.Handler.handleCallback(Unknown Source:2)
01-04 13:01:14.700 24332 24332 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Unknown Source:4)
01-04 13:01:14.700 24332 24332 E AndroidRuntime: 	at android.os.Looper.loop(Unknown Source:242)
01-04 13:01:14.700 24332 24332 E AndroidRuntime: 	at android.app.ActivityThread.main(Unknown Source:98)
01-04 13:01:14.700 24332 24332 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-04 13:01:14.700 24332 24332 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
01-04 13:01:14.700 24332 24332 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(Unknown Source:275)
01-04 13:01:22.662 24453 24571 I AndroidRuntime: VM exiting with result code 0, cleanup skipped.
```

**Comment by cmeng-git** [comment]
I really do not understand why this is happening. Below is the actual source doing the chat Room groups expansion. getGroupCount() is the android SDK library call. From the exception, it seems that the group source 1 & 8 are unknown to android OS.

May I know how many active user accounts did you registered and running at the moment of system crash; and how many chatRooms you have created in total for all the accounts?

```
    /**
     * Expands all contained groups.
     */
    public void expandAllGroups()
    {
        // Expand group view only when chatRoomListView is in focus (UI mode)
        // cmeng - do not use isFocused() - may not in sync with actual
        uiHandler.post(() -> {
            int count = getGroupCount();
            for (int position = 0; position < count; position++)
                if (chatRoomListView != null)
                    chatRoomListView.expandGroup(position);
        });
    }
```

**Comment by licaon-kter** [comment]
1 account
1 contact
2 rooms unopened, not autojoined

**Comment by cmeng-git** [comment]
Seems like there is some problem with the aTalk database. From exceptions, it indicates that you have 9 accounts, possibly due to earlier problems that has led to an unclean database.

It will be good, if I can study the actual database to understand the actual cause and find a solution.
Are you ok to send me the actual database i.e. /data/data/org.atalk.android/databases/dbRecords.db
The table name is "chatSessions".

Otherwise, in order to resolve the problem, you may need to  reinstall aTalk with a new database.

**Comment by licaon-kter** [comment]
Unfortunately I've cleaned up data to test https://github.com/cmeng-git/atalk-android/issues/84 again

**Comment by licaon-kter** [comment]
I can repro this if I touch my contact to open its chat too fast.

Can you contact me via XMPP so I'd give you that file?

**Comment by cmeng-git** [comment]
> I can repro this if I touch my contact to open its chat too fast.

Can you elaborate on this?
Did you click on the contact to open a chat session before the user/account has registered (login) with the server?.

**Comment by licaon-kter** [comment]
Looks like I can't repro at will.

My circle is green so online, my contact is orange, so I guess login has been done already.

One different thing, at first it says "Please wait..." on the loading screen but after the crash it says "Restoring..."

**Comment by cmeng-git** [comment]
aTalk will restore itself to working condition on system crashes. This is what you have observed.

**Comment by cmeng-git** [comment]
Unable to reproduce the problem. Raise/Reopen the issue if encountered again.
