### ISSUE TITLE
Privacy Policy can not be found

### ISSUE THREAD

**Issue by MilanKral** [cmeng-git/atalk-android#93]
The link 
http://atalk.sytes.net/privacypolicy.html
in
https://github.com/cmeng-git/atalk-android/blob/master/README.md

returns 404 Not Found

**Comment by cmeng-git** [comment]
Sorry the correct link should be 
https://cmeng-git.github.io/privacypolicy.html

Will update the link for next release

**Comment by cmeng-git** [comment]
Update in v2.1.7
